//****************************************************************
// Copyright (C), 2001 MMSoft, All rights reserved
//****************************************************************

//****************************************************************
//
// SOURCE FILE: cfg.h
//
// MODULE NAME: common (Software)
//
// PURPOSE:     Software dependent configuration.
//
// AUTHOR:      Marek Mikolajewski (MM)
//
// REVIEWED BY:
//
// HISTORY:     Ver   Date       Sign   Description
//
//              001    6-12-2001 MM     Created
//
//****************************************************************

#ifndef __CFG_H__
  #define __CFG_H__

#define __SIO2IDE_VER__        0x44     // Software version
#define __SIO2IDE_VER_TXT__    "4.4"    //

#endif  // __CFG_H__
