//****************************************************************
// Copyright (C), 2001 MMSoft, All rights reserved
//****************************************************************

//****************************************************************
//
// SOURCE FILE: apps.h
//
// MODULE NAME: common
//
// PURPOSE:     Common application header file.
//
// AUTHOR:      Marek Mikolajewski (MM)
//
// REVIEWED BY:
//
// HISTORY:     Ver   Date       Sign   Description
//
//              001    6-12-2001 MM     Created
//
//****************************************************************

#ifndef __APPS_H__
  #define __APPS_H__

#include "platform.h"           // Platform

#include "cfg.h"                // SW Config

#include "ide.h"                // IDE driver
#include "sio.h"                // SIO driver
#include "fs.h"                 // SIO2IDE FS

#endif  // __APPS_H__
