;
; File generated by cc65 v 2.8.0
;
	.fopt		compiler,"cc65 v 2.8.0"
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "fdisk.c", 48693, 1279048568
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdlib.h", 4033, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stddef.h", 2865, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdio.h", 5323, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdarg.h", 3007, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/string.h", 4335, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/conio.h", 7309, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/atari.h", 9513, 1030607464
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_gtia.h", 5733, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pbi.h", 3057, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pokey.h", 4268, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pia.h", 2655, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_antic.h", 3412, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/ctype.h", 7873, 1018643664
	.dbg		file, "plat.h", 1225, 1279048568
	.dbg		file, "type.h", 1140, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/cfg.h", 800, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/ptable.h", 2129, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/direntry.h", 4014, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/iso.h", 8718, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/idestruc.h", 1307, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/fatstruc.h", 3099, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/siocmds.h", 2388, 1279048570
	.dbg		file, "keys.h", 865, 1279048568
	.dbg		file, "siosrv.h", 1744, 1279048568
	.dbg		file, "screen.h", 1856, 1279048568
	.dbg		file, "menu.h", 1328, 1279048568
	.dbg		file, "listv.h", 1458, 1279048568
	.dbg		file, "qsort.h", 847, 1279048568
	.import		_sprintf
	.import		_strcat
	.import		_strlen
	.import		_memcmp
	.import		_memcpy
	.import		_memset
	.import		_gotoxy
	.import		_SIO_GetFSInfo
	.import		_SIO_GetDriveInfo
	.import		_SIO_GetNextATR
	.import		_SIO_GetFirstATR
	.import		_SIO_PutDisk
	.import		_SIO_GetDisk
	.import		_SIO_DiskOff
	.import		_SIO_SaveConfig
	.import		_SIO_GetFirstDir
	.import		_SIO_GetNextDir
	.import		_SIO_SetCurDir
	.import		_SIO_GetCurDir
	.import		_SIO_InitCurDir
	.import		_SIO_GetLFN
	.import		_SCR_Init
	.import		_SCR_DeInit
	.import		_SCR_DrawFrame
	.import		_SCR_DrawWindow
	.import		_SCR_ProgressShow
	.import		_SCR_ProgressUpdate
	.import		_SCR_LoadShow
	.import		_SCR_LoadUpdate
	.import		_SCR_LineCenter
	.import		_SCR_LineCenterClr
	.import		_SCR_DrawLine
	.import		_WaitKey
	.import		_WaitKeyFor
	.import		_ShowCnfButton
	.import		_ShowYesNoButtons
	.import		_MENU_Show
	.import		_LISTV_Show
	.import		_QuickSort
	.import		_CardWait
	.export		_DrawMainMenu
	.export		_LoadMasterData
	.export		_LoadSlaveData
	.export		_DrawMainWindows
	.export		_DrawMainScreen
	.export		_main

.segment	"DATA"

_dID:
	.byte	$01
_upd:
	.byte	$00
_lfnON:
	.byte	$00
_cmpPos:
	.byte	$00

.segment	"RODATA"

L0001:
	.byte	$45,$72,$72,$6F,$72,$00,$53,$61,$76,$65,$20,$63,$6F,$6E,$66,$69
	.byte	$67,$20,$3F,$00,$4F,$4B,$00,$45,$72,$72,$6F,$72,$00,$49,$6E,$69
	.byte	$74,$69,$61,$6C,$69,$73,$69,$6E,$67,$00,$43,$75,$72,$72,$65,$6E
	.byte	$74,$20,$44,$49,$52,$00,$4F,$4B,$00,$45,$72,$72,$6F,$72,$00,$4E
	.byte	$6F,$74,$20,$53,$49,$4F,$32,$49,$44,$45,$20,$64,$69,$72,$00,$25
	.byte	$73,$20,$64,$69,$72,$65,$63,$74,$6F,$72,$79,$20,$20,$20,$3A,$20
	.byte	$3C,$25,$73,$3E,$00,$53,$49,$4F,$32,$49,$44,$45,$00,$55,$6E,$6B
	.byte	$6E,$6F,$77,$6E,$00,$50,$72,$65,$73,$73,$20,$27,$41,$27,$20,$74
	.byte	$6F,$20,$41,$63,$74,$69,$76,$61,$74,$65,$20,$63,$75,$72,$72,$65
	.byte	$6E,$74,$20,$44,$49,$52,$00,$50,$72,$65,$73,$73,$20,$27,$45,$73
	.byte	$63,$27,$20,$74,$6F,$20,$63,$6C,$6F,$73,$65,$00,$52,$65,$61,$64
	.byte	$69,$6E,$67,$20,$64,$61,$74,$61,$00,$44,$69,$65,$72,$65,$63,$74
	.byte	$6F,$72,$69,$65,$73,$00,$2E,$20,$20,$20,$20,$20,$20,$20,$00,$00
	.byte	$1B,$00,$41,$61,$00,$45,$72,$72,$6F,$72,$00,$45,$72,$72,$6F,$72
	.byte	$00,$41,$63,$74,$69,$76,$65,$20,$64,$69,$72,$65,$63,$74,$6F,$72
	.byte	$79,$20,$20,$20,$20,$3A,$20,$3C,$25,$73,$3E,$00,$25,$73,$20,$64
	.byte	$69,$72,$65,$63,$74,$6F,$72,$79,$20,$3A,$20,$3C,$25,$73,$3E,$00
	.byte	$53,$49,$4F,$32,$49,$44,$45,$00,$55,$6E,$6B,$6E,$6F,$77,$6E,$00
	.byte	$45,$72,$72,$6F,$72,$00,$45,$72,$72,$6F,$72,$00,$20,$44,$25,$64
	.byte	$3A,$20,$3C,$20,$25,$73,$20,$25,$73,$20,$25,$35,$75,$20,$73,$65
	.byte	$63,$74,$6F,$72,$73,$20,$25,$73,$00,$52,$4F,$00,$52,$57,$00,$32
	.byte	$35,$36,$42,$00,$31,$32,$38,$42,$00,$20,$44,$25,$64,$3A,$20,$20
	.byte	$20,$25,$73,$00,$4E,$4F,$54,$20,$41,$6C,$6C,$6F,$77,$65,$64,$00
	.byte	$4F,$4B,$00,$45,$72,$72,$6F,$72,$00,$44,$69,$73,$6B,$20,$64,$65
	.byte	$74,$61,$69,$6C,$73,$00,$41,$74,$61,$72,$69,$20,$44,$69,$73,$6B
	.byte	$20,$20,$20,$3A,$20,$44,$25,$64,$00,$41,$74,$61,$72,$69,$20,$44
	.byte	$69,$73,$6B,$20,$20,$20,$3A,$20,$43,$6F,$6D,$6D,$6F,$6E,$20,$28
	.byte	$44,$31,$3A,$29,$00,$53,$74,$61,$72,$74,$20,$73,$65,$63,$74,$6F
	.byte	$72,$20,$3A,$20,$25,$6C,$75,$00,$2E,$61,$74,$72,$00,$44,$49,$53
	.byte	$4B,$20,$53,$4C,$4F,$54,$20,$44,$25,$64,$20,$49,$53,$20,$45,$4D
	.byte	$50,$54,$59,$00,$44,$49,$53,$4B,$20,$53,$4C,$4F,$54,$20,$28,$43
	.byte	$6F,$6D,$6D,$6F,$6E,$29,$20,$49,$53,$20,$45,$4D,$50,$54,$59,$00
	.byte	$50,$72,$65,$73,$73,$20,$27,$57,$27,$20,$74,$6F,$20,$6D,$61,$72
	.byte	$6B,$20,$44,$69,$73,$6B,$20,$61,$73,$20,$57,$72,$69,$74,$61,$62
	.byte	$6C,$65,$20,$00,$50,$72,$65,$73,$73,$20,$27,$52,$27,$20,$74,$6F
	.byte	$20,$6D,$61,$72,$6B,$20,$44,$69,$73,$6B,$20,$61,$73,$20,$52,$65
	.byte	$61,$64,$20,$4F,$6E,$6C,$79,$00,$50,$72,$65,$73,$73,$20,$27,$45
	.byte	$73,$63,$27,$20,$74,$6F,$20,$63,$6C,$6F,$73,$65,$00,$41,$74,$61
	.byte	$72,$69,$20,$64,$69,$73,$6B,$73,$00,$1B,$00,$52,$72,$57,$77,$00
	.byte	$27,$45,$73,$63,$27,$20,$74,$6F,$20,$63,$6C,$6F,$73,$65,$2C,$20
	.byte	$27,$53,$70,$61,$63,$65,$27,$20,$4C,$46,$4E,$2D,$25,$73,$00,$4F
	.byte	$66,$66,$00,$4F,$6E,$20,$00,$41,$54,$52,$20,$66,$69,$6C,$65,$20
	.byte	$64,$65,$74,$61,$69,$6C,$73,$00,$2E,$61,$74,$72,$00,$46,$69,$6C
	.byte	$65,$20,$3A,$20,$25,$64,$00,$4D,$6F,$64,$65,$20,$3A,$20,$25,$73
	.byte	$00,$52,$4F,$00,$52,$57,$00,$53,$69,$7A,$65,$20,$28,$73,$65,$63
	.byte	$74,$6F,$72,$73,$29,$20,$3A,$20,$25,$75,$00,$53,$65,$63,$74,$6F
	.byte	$72,$20,$73,$69,$7A,$65,$20,$20,$20,$20,$3A,$20,$25,$73,$00,$32
	.byte	$35,$36,$42,$00,$31,$32,$38,$42,$00,$00,$1B,$00,$20,$41,$42,$43
	.byte	$44,$45,$46,$47,$48,$49,$4A,$4B,$4C,$4D,$4E,$4F,$50,$51,$52,$53
	.byte	$54,$55,$56,$57,$58,$59,$5A,$61,$62,$63,$64,$65,$66,$67,$68,$69
	.byte	$6A,$6B,$6C,$6D,$6E,$6F,$70,$71,$72,$73,$74,$75,$76,$77,$78,$79
	.byte	$7A,$00,$50,$72,$65,$73,$73,$20,$27,$45,$73,$63,$27,$20,$74,$6F
	.byte	$20,$63,$6C,$6F,$73,$65,$00,$44,$69,$73,$6B,$20,$44,$72,$69,$76
	.byte	$65,$20,$70,$61,$72,$61,$6D,$65,$74,$65,$72,$73,$00,$48,$44,$44
	.byte	$20,$6D,$6F,$64,$65,$20,$20,$20,$20,$20,$20,$3A,$20,$25,$73,$00
	.byte	$4C,$42,$41,$00,$43,$48,$53,$00,$48,$65,$61,$64,$73,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$3A,$20,$25,$64,$00,$43,$79,$6C,$69,$6E
	.byte	$64,$65,$72,$73,$20,$20,$20,$20,$20,$3A,$20,$25,$64,$00,$53,$65
	.byte	$63,$20,$70,$65,$72,$20,$54,$72,$61,$63,$6B,$20,$3A,$20,$25,$64
	.byte	$00,$53,$65,$63,$74,$6F,$72,$73,$20,$20,$20,$20,$20,$20,$20,$3A
	.byte	$20,$25,$6C,$75,$00,$49,$6E,$74,$65,$72,$66,$61,$63,$65,$20,$70
	.byte	$61,$72,$61,$6D,$65,$74,$65,$72,$73,$00,$44,$65,$76,$69,$63,$65
	.byte	$20,$6D,$6F,$64,$65,$20,$20,$20,$3A,$20,$25,$73,$00,$4D,$41,$53
	.byte	$54,$45,$52,$00,$53,$4C,$41,$56,$45,$00,$53,$6F,$66,$74,$20,$76
	.byte	$65,$72,$73,$69,$6F,$6E,$20,$20,$3A,$20,$25,$64,$2E,$25,$64,$00
	.byte	$41,$54,$52,$20,$66,$69,$6C,$65,$73,$20,$20,$20,$20,$20,$3A,$20
	.byte	$25,$64,$00,$50,$61,$72,$74,$2E,$20,$74,$79,$70,$65,$20,$20,$20
	.byte	$20,$3A,$20,$00,$46,$41,$54,$31,$36,$20,$73,$6D,$61,$6C,$6C,$00
	.byte	$46,$41,$54,$31,$36,$20,$62,$69,$67,$00,$46,$41,$54,$33,$32,$20
	.byte	$4C,$42,$41,$00,$49,$53,$4F,$39,$36,$36,$30,$00,$55,$6E,$6B,$6E
	.byte	$6F,$77,$6E,$00,$53,$65,$63,$20,$70,$65,$72,$20,$43,$6C,$75,$73
	.byte	$74,$20,$3A,$20,$25,$64,$00,$1B,$00,$41,$54,$52,$20,$66,$69,$6C
	.byte	$65,$73,$20,$76,$69,$65,$77,$65,$72,$00,$4F,$4B,$00,$45,$72,$72
	.byte	$6F,$72,$00,$43,$3A,$28,$52,$4F,$4F,$54,$29,$00,$4E,$6F,$74,$20
	.byte	$52,$4F,$4F,$54,$20,$64,$69,$72,$00,$53,$65,$6C,$65,$63,$74,$20
	.byte	$41,$54,$52,$20,$66,$69,$6C,$65,$20,$66,$6F,$72,$20,$44,$25,$64
	.byte	$3A,$00,$44,$69,$73,$6B,$20,$4F,$46,$46,$20,$3F,$00,$2D,$2D,$2D
	.byte	$2D,$2D,$2D,$2D,$2D,$00,$4F,$4B,$00,$45,$72,$72,$6F,$72,$00,$4E
	.byte	$4F,$54,$20,$41,$6C,$6C,$6F,$77,$65,$64,$00,$4F,$4B,$00,$45,$72
	.byte	$72,$6F,$72,$00,$41,$63,$74,$69,$76,$65,$20,$64,$69,$72,$65,$63
	.byte	$74,$6F,$72,$79,$20,$3A,$20,$25,$2E,$38,$73,$00,$53,$65,$6C,$65
	.byte	$63,$74,$20,$6F,$70,$74,$69,$6F,$6E,$00,$20,$50,$20,$2D,$20,$56
	.byte	$69,$65,$77,$20,$70,$61,$72,$61,$6D,$65,$74,$65,$72,$73,$00,$50
	.byte	$70,$00,$20,$44,$20,$2D,$20,$43,$68,$61,$6E,$67,$65,$20,$61,$63
	.byte	$74,$69,$76,$65,$20,$44,$49,$52,$00,$44,$64,$00,$20,$56,$20,$2D
	.byte	$20,$56,$69,$65,$77,$20,$41,$54,$52,$20,$66,$69,$6C,$65,$73,$00
	.byte	$56,$76,$00,$20,$41,$20,$2D,$20,$41,$73,$73,$69,$67,$6E,$20,$44
	.byte	$69,$73,$6B,$00,$41,$61,$00,$20,$53,$20,$2D,$20,$53,$61,$76,$65
	.byte	$20,$63,$6F,$6E,$66,$69,$67,$75,$72,$61,$74,$69,$6F,$6E,$00,$53
	.byte	$73,$00,$20,$1B,$20,$2D,$20,$45,$78,$69,$74,$00,$1B,$00,$00,$00
	.byte	$4D,$61,$69,$6E,$20,$6D,$65,$6E,$75,$00,$00,$43,$6F,$6E,$66,$69
	.byte	$67,$75,$72,$61,$74,$69,$6F,$6E,$00,$57,$72,$6F,$6E,$67,$20,$53
	.byte	$57,$20,$76,$65,$72,$73,$69,$6F,$6E,$00,$41,$74,$61,$72,$69,$20
	.byte	$64,$69,$73,$6B,$73,$00,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$00,$41
	.byte	$54,$52,$20,$66,$69,$6C,$65,$73,$00,$53,$6F,$72,$74,$69,$6E,$67
	.byte	$20,$66,$69,$6C,$65,$73,$00,$44,$6F,$6E,$65,$00,$52,$65,$61,$64
	.byte	$69,$6E,$67,$20,$64,$61,$74,$61,$00,$4F,$4B,$00,$53,$61,$76,$65
	.byte	$20,$63,$6F,$6E,$66,$69,$67,$20,$3F,$00,$45,$72,$72,$6F,$72,$00
	.byte	$4D,$4D,$53,$6F,$66,$74,$20,$28,$63,$29,$20,$32,$30,$30,$35,$20
	.byte	$20,$28,$43,$61,$72,$74,$20,$76,$65,$72,$73,$69,$6F,$6E,$29,$00
	.byte	$53,$49,$4F,$32,$49,$44,$45,$20,$34,$2E,$34,$20,$63,$6F,$6E,$66
	.byte	$69,$67,$75,$72,$61,$74,$69,$6F,$6E,$20,$63,$65,$6E,$74,$65,$72
	.byte	$00,$53,$49,$4F,$32,$49,$44,$45,$20,$34,$2E,$34,$20,$42,$6F,$6F
	.byte	$74,$4C,$6F,$61,$64,$65,$72,$00,$20,$4D,$20,$2D,$20,$4D,$61,$73
	.byte	$74,$65,$72,$20,$64,$65,$76,$69,$63,$65,$00,$4D,$6D,$00,$20,$53
	.byte	$20,$2D,$20,$53,$6C,$61,$76,$65,$20,$64,$65,$76,$69,$63,$65,$00
	.byte	$53,$73,$00,$20,$1B,$20,$2D,$20,$45,$78,$69,$74,$00,$1B,$00,$00
	.byte	$00,$53,$65,$6C,$65,$63,$74,$20,$69,$6E,$74,$65,$72,$66,$61,$63
	.byte	$65,$00,$00,$57,$61,$69,$74,$20,$66,$6F,$72,$20,$64,$69,$73,$6B
	.byte	$20,$42,$4F,$4F,$54,$00,$A0,$C5,$F3,$E3,$A0,$20,$20,$2D,$20,$53
	.byte	$49,$4F,$32,$49,$44,$45,$20,$73,$65,$74,$75,$70,$00,$D3,$F0,$E1
	.byte	$E3,$E5,$20,$20,$2D,$20,$73,$6B,$69,$70,$20,$73,$65,$74,$75,$70
	.byte	$20,$20,$20,$00,$1B,$20,$00,$4C,$65,$61,$76,$65,$20,$43,$41,$52
	.byte	$54,$20,$4F,$4E,$20,$3F,$00,$53,$77,$69,$74,$63,$68,$20,$4F,$46
	.byte	$46,$20,$74,$68,$65,$20,$43,$41,$52,$54,$00

.segment	"BSS"

_drvInfo:
	.res	10,$00
_fsInfo:
	.res	4,$00
_atrInd:
	.res	402,$00
_atrTab:
	.res	3015,$00
_diskTab:
	.res	135,$00
_dirTab:
	.res	765,$00
_actDir:
	.res	15,$00
_selDir:
	.res	15,$00
_maxDirs:
	.res	2,$00
_maxFiles:
	.res	2,$00
_cmpBuf:
	.res	8,$00
_curDisk:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char InitData (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_InitData

	.dbg	line, "fdisk.c", 1454
	ldy     #$16
	jsr     subysp
	lda     #<(_diskTab)
	ldx     #>(_diskTab)
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$87
	jsr     _memset
	.dbg	line, "fdisk.c", 1455
	lda     #<(_atrTab)
	ldx     #>(_atrTab)
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	ldx     #$0B
	lda     #$C7
	jsr     _memset
	.dbg	line, "fdisk.c", 1458
	ldx     #$00
	txa
L0746:	ldy     #$14
	jsr     staxysp
	ldy     #$15
	lda     (sp),y
	cmp     #$00
	bne     L063A
	dey
	lda     (sp),y
	cmp     #$C8
L063A:	bcs     L0634
	.dbg	line, "fdisk.c", 1460
	ldy     #$15
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	jsr     pushax
	ldy     #$17
	jsr     ldaxysp
	ldy     #$00
	jsr     staxspidx
	.dbg	line, "fdisk.c", 1458
	ldy     #$15
	jsr     ldaxysp
	jsr     incax1
	jmp     L0746
	.dbg	line, "fdisk.c", 1467
L0634:	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1468
	lda     #<(L0001+1482)
	ldx     #>(L0001+1482)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 1469
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$0B
	jsr     pusha
	lda     #$09
	jsr     pusha
	lda     #$0F
	jsr     pusha
	ldx     #$00
	lda     #$09
	jsr     pushax
	jsr     _SCR_ProgressShow
	.dbg	line, "fdisk.c", 1471
	ldx     #$00
	txa
L0747:	ldy     #$14
	jsr     staxysp
	ldy     #$15
	lda     (sp),y
	cmp     #$00
	bne     L0652
	dey
	lda     (sp),y
	cmp     #$09
L0652:	jcs     L064C
	.dbg	line, "fdisk.c", 1473
	ldy     #$16
	lda     (sp),y
	jsr     pusha
	ldy     #$16
	jsr     ldaxysp
	jsr     incax1
	jsr     pusha
	ldy     #$17
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	jsr     _SIO_GetDisk
	tax
	.dbg	line, "fdisk.c", 1474
	jeq     L0628
	.dbg	line, "fdisk.c", 1476
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$17
	jsr     ldaxysp
	jsr     incax1
	jsr     pushax
	jsr     _SCR_ProgressUpdate
	.dbg	line, "fdisk.c", 1478
	ldy     #$15
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	bne     L064D
	.dbg	line, "fdisk.c", 1480
	ldy     #$15
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	lda     #<(L0001+1494)
	ldx     #>(L0001+1494)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 1471
L064D:	ldy     #$15
	jsr     ldaxysp
	jsr     incax1
	jmp     L0747
	.dbg	line, "fdisk.c", 1487
L064C:	lda     #$00
	sta     _maxFiles
	sta     _maxFiles+1
	.dbg	line, "fdisk.c", 1489
	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1490
	lda     #<(L0001+1503)
	ldx     #>(L0001+1503)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 1491
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$0B
	jsr     pusha
	lda     #$09
	jsr     pusha
	lda     #$0F
	jsr     pusha
	jsr     _SCR_LoadShow
	.dbg	line, "fdisk.c", 1493
	ldy     #$16
	lda     (sp),y
	jsr     pusha
	lda     #$06
	jsr     leaasp
	jsr     pushax
	jsr     _SIO_GetFirstATR
	tax
	jeq     L0628
	.dbg	line, "fdisk.c", 1498
L0678:	lda     _maxFiles+1
	cmp     #$00
	bne     L067C
	lda     _maxFiles
	cmp     #$C8
	.dbg	line, "fdisk.c", 1500
L067C:	bcs     L0679
	.dbg	line, "fdisk.c", 1502
	ldy     #$13
	lda     (sp),y
	and     #$80
	.dbg	line, "fdisk.c", 1504
	beq     L0679
	.dbg	line, "fdisk.c", 1507
	lda     _maxFiles
	ldx     _maxFiles+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     _maxFiles
	stx     _maxFiles+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	lda     #$07
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 1509
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     _maxFiles
	ldx     _maxFiles+1
	jsr     pushax
	jsr     _SCR_LoadUpdate
	.dbg	line, "fdisk.c", 1511
	ldy     #$16
	lda     (sp),y
	jsr     pusha
	lda     #$06
	jsr     leaasp
	jsr     pushax
	jsr     _SIO_GetNextATR
	tax
	bne     L0678
	.dbg	line, "fdisk.c", 1515
L0679:	lda     _maxFiles+1
	cmp     #$00
	bne     L068B
	lda     _maxFiles
	cmp     #$02
L068B:	bcc     L0689
	.dbg	line, "fdisk.c", 1517
	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1518
	lda     #<(L0001+1513)
	ldx     #>(L0001+1513)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 1520
	ldx     #$00
	txa
	jsr     pushax
	lda     _maxFiles
	ldx     _maxFiles+1
	jsr     decax1
	jsr     pushax
	lda     #<(_CmpATR)
	ldx     #>(_CmpATR)
	jsr     pushax
	lda     #<(_SwpATR)
	ldx     #>(_SwpATR)
	jsr     pushax
	jsr     _QuickSort
	.dbg	line, "fdisk.c", 1523
L0689:	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1524
	lda     #<(L0001+1527)
	ldx     #>(L0001+1527)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 1526
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1547
L0628:	ldy     #$17
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SaveConfig (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_SaveConfig

	.dbg	line, "fdisk.c", 1301
	lda     _fsInfo
	cmp     #$7F
	bne     L057D
	.dbg	line, "fdisk.c", 1303
	lda     #<(L0001+1247)
	ldx     #>(L0001+1247)
	.dbg	line, "fdisk.c", 1304
	jmp     L074C
	.dbg	line, "fdisk.c", 1306
L057D:	lda     _dID
	jsr     pusha
	jsr     _SIO_SaveConfig
	tax
	beq     L0583
	.dbg	line, "fdisk.c", 1308
	lda     #<(L0001+1259)
	ldx     #>(L0001+1259)
	jsr     pushax
	lda     #$0E
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1310
	lda     #$00
	sta     _upd
	.dbg	line, "fdisk.c", 1312
	jmp     L058B
	.dbg	line, "fdisk.c", 1314
L0583:	lda     #<(L0001+1262)
	ldx     #>(L0001+1262)
L074C:	jsr     pushax
	lda     #$0E
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1316
L058B:	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1317
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned int DirCnt (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DirCnt

	.dbg	line, "fdisk.c", 319
	lda     _maxDirs
	ldx     _maxDirs+1
	.dbg	line, "fdisk.c", 320
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char DirItm (unsigned char**, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DirItm

	.dbg	line, "fdisk.c", 330
	ldy     #$03
	jsr     pushwysp
	lda     _maxDirs
	ldx     _maxDirs+1
	jsr     tosicmp
	bcs     L00DD
	.dbg	line, "fdisk.c", 332
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	ldy     #$00
	jsr     staxspidx
	.dbg	line, "fdisk.c", 333
	ldx     #$00
	lda     #$01
	jmp     incsp4
	.dbg	line, "fdisk.c", 335
L00DD:	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 336
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char OnDirSelect (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_OnDirSelect

	.dbg	line, "fdisk.c", 346
	ldy     #$03
	jsr     pushwysp
	lda     _maxDirs
	ldx     _maxDirs+1
	jsr     tosicmp
	bcs     L00E5
	.dbg	line, "fdisk.c", 348
	lda     _dID
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	jsr     _SIO_SetCurDir
	tax
	bne     L00E7
	.dbg	line, "fdisk.c", 350
	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 351
	jmp     L00E5
	.dbg	line, "fdisk.c", 353
L00E7:	lda     #<(_selDir)
	ldx     #>(_selDir)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 355
L00E5:	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 356
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char OnDirAction (unsigned int*, unsigned char, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_OnDirAction

	.dbg	line, "fdisk.c", 368
	ldy     #$0F
	jsr     subysp
	ldy     #$10
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
	.dbg	line, "fdisk.c", 369
	ldy     #$11
	lda     (sp),y
	sta     (sp),y
	.dbg	line, "fdisk.c", 370
	ldy     #$13
	jsr     ldaxysp
	ldy     #$12
	jsr     staxysp
	.dbg	line, "fdisk.c", 372
	lda     _upd
	beq     L010C
	lda     _fsInfo
	cmp     #$7F
	beq     L010C
	.dbg	line, "fdisk.c", 374
	lda     #<(L0001+6)
	ldx     #>(L0001+6)
	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowYesNoButtons
	tax
	beq     L010C
	.dbg	line, "fdisk.c", 376
	lda     _dID
	jsr     pusha
	jsr     _SIO_SaveConfig
	tax
	beq     L0104
	.dbg	line, "fdisk.c", 378
	lda     #<(L0001+20)
	ldx     #>(L0001+20)
	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 380
	lda     #$00
	sta     _upd
	.dbg	line, "fdisk.c", 382
	jmp     L010C
	.dbg	line, "fdisk.c", 384
L0104:	lda     #<(L0001+23)
	ldx     #>(L0001+23)
	.dbg	line, "fdisk.c", 385
	jmp     L0755
	.dbg	line, "fdisk.c", 390
L010C:	lda     _selDir+14
	and     #$01
	jeq     L0111
	.dbg	line, "fdisk.c", 392
	lda     #<(L0001+29)
	ldx     #>(L0001+29)
	jsr     pushax
	lda     #$09
	jsr     pusha
	lda     #$05
	jsr     pusha
	lda     #$1D
	jsr     pusha
	lda     #$0C
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 394
	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 395
	lda     #<(L0001+42)
	ldx     #>(L0001+42)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 397
	lda     _dID
	jsr     pusha
	lda     #$01
	jsr     leaasp
	jsr     pushax
	jsr     _SIO_InitCurDir
	tax
	beq     L0125
	.dbg	line, "fdisk.c", 402
	ldy     #$0E
	lda     (sp),y
	and     #$02
	beq     L0125
	.dbg	line, "fdisk.c", 404
	lda     _dID
	jsr     pusha
	jsr     _InitData
	tax
	beq     L0125
	.dbg	line, "fdisk.c", 406
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 408
	lda     #<(L0001+54)
	ldx     #>(L0001+54)
	jsr     pushax
	lda     #$0D
	.dbg	line, "fdisk.c", 409
	jmp     L0754
	.dbg	line, "fdisk.c", 413
L0125:	lda     #<(L0001+57)
	ldx     #>(L0001+57)
	.dbg	line, "fdisk.c", 415
	jmp     L0755
	.dbg	line, "fdisk.c", 417
L0111:	lda     #<(L0001+63)
	ldx     #>(L0001+63)
L0755:	jsr     pushax
	lda     #$09
L0754:	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 419
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 420
	ldy     #$14
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DirDummyFoc (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DirDummyFoc

	.dbg	line, "fdisk.c", 433
	ldy     #$34
	jsr     subysp
	ldy     #$37
	jsr     pushwysp
	lda     _maxDirs
	ldx     _maxDirs+1
	jsr     tosicmp
	jcs     L0139
	.dbg	line, "fdisk.c", 435
	lda     #$03
	jsr     pusha
	lda     #$11
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 436
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0C
	jsr     _memset
	.dbg	line, "fdisk.c", 437
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$37
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 438
	lda     #$0C
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+79)
	ldx     #>(L0001+79)
	jsr     pushax
	.dbg	line, "fdisk.c", 439
	ldy     #$39
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	sta     ptr1
	txa
	adc     #>(_dirTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$01
	beq     L014E
	lda     #<(L0001+101)
	ldx     #>(L0001+101)
	jmp     L0150
L014E:	lda     #<(L0001+109)
	ldx     #>(L0001+109)
L0150:	jsr     pushax
	.dbg	line, "fdisk.c", 440
	lda     #$06
	jsr     leaasp
	jsr     pushax
	ldy     #$08
	jsr     _sprintf
	.dbg	line, "fdisk.c", 441
	lda     #$0C
	jsr     leaasp
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 443
L0139:	ldy     #$36
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawDirList (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawDirList

	.dbg	line, "fdisk.c", 453
	lda     #$00
	jsr     pusha
	lda     #$14
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 454
	lda     #$01
	jsr     pusha
	lda     #$15
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 455
	lda     #<(L0001+117)
	ldx     #>(L0001+117)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 456
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 457
	lda     #<(L0001+151)
	ldx     #>(L0001+151)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jmp     _SCR_LineCenter
	.dbg	line

.endproc

; ---------------------------------------------------------------
; signed short CmpDir (signed short, signed short)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_CmpDir

	.dbg	line, "fdisk.c", 468
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcmp
	.dbg	line, "fdisk.c", 469
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void SwpDir (signed short, signed short)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_SwpDir

	.dbg	line, "fdisk.c", 481
	ldy     #$0F
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$14
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 482
	ldy     #$12
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldy     #$12
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 483
	ldy     #$10
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 484
	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char ReadDirs (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_ReadDirs

	.dbg	line, "fdisk.c", 498
	ldy     #$14
	jsr     subysp
	lda     #<(_dirTab)
	ldx     #>(_dirTab)
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	ldx     #$02
	lda     #$FD
	jsr     _memset
	.dbg	line, "fdisk.c", 501
	lda     #<(L0001+172)
	ldx     #>(L0001+172)
	jsr     pushax
	lda     #$09
	jsr     pusha
	lda     #$05
	jsr     pusha
	lda     #$1D
	jsr     pusha
	lda     #$0C
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 503
	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 504
	lda     #<(L0001+185)
	ldx     #>(L0001+185)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 505
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$0B
	jsr     pusha
	lda     #$09
	jsr     pusha
	lda     #$0F
	jsr     pusha
	jsr     _SCR_LoadShow
	.dbg	line, "fdisk.c", 507
	lda     #$00
	sta     _maxDirs
	sta     _maxDirs+1
	.dbg	line, "fdisk.c", 509
	ldy     #$14
	lda     (sp),y
	jsr     pusha
	lda     #$06
	jsr     leaasp
	jsr     pushax
	jsr     _SIO_GetFirstDir
	tax
	jeq     L017B
	.dbg	line, "fdisk.c", 514
L0198:	lda     _maxDirs+1
	cmp     #$00
	bne     L019C
	lda     _maxDirs
	cmp     #$32
	.dbg	line, "fdisk.c", 516
L019C:	jcs     L0199
	.dbg	line, "fdisk.c", 518
	ldy     #$13
	lda     (sp),y
	and     #$02
	.dbg	line, "fdisk.c", 520
	jeq     L0199
	.dbg	line, "fdisk.c", 523
	lda     #$05
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+198)
	ldx     #>(L0001+198)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcmp
	cpx     #$00
	bne     L0757
	cmp     #$00
	beq     L01A0
	.dbg	line, "fdisk.c", 525
L0757:	lda     _maxDirs
	ldx     _maxDirs+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     _maxDirs
	stx     _maxDirs+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_dirTab)
	tay
	txa
	adc     #>(_dirTab)
	tax
	tya
	jsr     pushax
	lda     #$07
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 527
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     _maxDirs
	ldx     _maxDirs+1
	jsr     pushax
	jsr     _SCR_LoadUpdate
	.dbg	line, "fdisk.c", 530
L01A0:	ldy     #$14
	lda     (sp),y
	jsr     pusha
	lda     #$06
	jsr     leaasp
	jsr     pushax
	jsr     _SIO_GetNextDir
	tax
	jne     L0198
	.dbg	line, "fdisk.c", 534
L0199:	lda     _maxDirs+1
	cmp     #$00
	bne     L01B1
	lda     _maxDirs
	cmp     #$02
L01B1:	bcc     L01AF
	.dbg	line, "fdisk.c", 536
	ldx     #$00
	txa
	jsr     pushax
	lda     _maxDirs
	ldx     _maxDirs+1
	jsr     decax1
	jsr     pushax
	lda     #<(_CmpDir)
	ldx     #>(_CmpDir)
	jsr     pushax
	lda     #<(_SwpDir)
	ldx     #>(_SwpDir)
	jsr     pushax
	jsr     _QuickSort
	.dbg	line, "fdisk.c", 539
L01AF:	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 554
L017B:	ldy     #$15
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char ViewDirectories (void)
; ---------------------------------------------------------------

.segment	"DATA"

L01BC:
	.byte	$00
	.addr	L0001+207
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$27
	.byte	$0F
	.addr	L0001+208
	.addr	L0001+210
	.addr	_DirCnt
	.addr	_DirItm
	.addr	_OnDirSelect
	.addr	_OnDirAction
	.addr	_DirDummyFoc
	.addr	_DrawDirList

.segment	"CODE1"

.proc	_ViewDirectories

	.dbg	line, "fdisk.c", 574
	ldy     #$35
	jsr     subysp
	lda     _dID
	jsr     pusha
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	jsr     _SIO_GetCurDir
	tax
	bne     L01CC
	.dbg	line, "fdisk.c", 576
	lda     #<(L0001+213)
	ldx     #>(L0001+213)
	.dbg	line, "fdisk.c", 577
	jmp     L075C
	.dbg	line, "fdisk.c", 579
L01CC:	lda     _actDir+14
	and     #$02
	bne     L01D4
	.dbg	line, "fdisk.c", 581
	lda     #<(L0001+219)
	ldx     #>(L0001+219)
	.dbg	line, "fdisk.c", 582
	jmp     L075C
	.dbg	line, "fdisk.c", 584
L01D4:	lda     #<(_selDir)
	ldx     #>(_selDir)
	jsr     pushax
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 586
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$0F
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 588
	lda     #$9B
	ldy     #$00
	sta     (sp),y
	.dbg	line, "fdisk.c", 591
L01E5:	tya
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$13
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 592
	lda     #$03
	jsr     pusha
	lda     #$12
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 593
	lda     #$29
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0C
	jsr     _memset
	.dbg	line, "fdisk.c", 594
	lda     #$29
	jsr     leaasp
	jsr     pushax
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 595
	lda     #$01
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+225)
	ldx     #>(L0001+225)
	jsr     pushax
	lda     #$2D
	jsr     leaasp
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 596
	lda     #$01
	jsr     leaasp
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 598
	ldy     #$00
	lda     (sp),y
	cmp     #$9B
	bne     L0203
	lda     _dID
	jsr     pusha
	jsr     _ReadDirs
	jmp     L0206
L0203:	lda     #$01
L0206:	beq     L0200
	.dbg	line, "fdisk.c", 600
	lda     #$29
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0C
	jsr     _memset
	.dbg	line, "fdisk.c", 601
	lda     #$29
	jsr     leaasp
	jsr     pushax
	lda     #<(_selDir)
	ldx     #>(_selDir)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 602
	lda     #$01
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+252)
	ldx     #>(L0001+252)
	jsr     pushax
	.dbg	line, "fdisk.c", 603
	lda     _selDir+14
	and     #$01
	beq     L0217
	lda     #<(L0001+272)
	ldx     #>(L0001+272)
	jmp     L0219
L0217:	lda     #<(L0001+280)
	ldx     #>(L0001+280)
L0219:	jsr     pushax
	.dbg	line, "fdisk.c", 604
	lda     #$2F
	jsr     leaasp
	jsr     pushax
	ldy     #$08
	jsr     _sprintf
	.dbg	line, "fdisk.c", 606
	lda     #$01
	jsr     leaasp
	sta     L01BC+1
	stx     L01BC+1+1
	.dbg	line, "fdisk.c", 607
	lda     #<(L01BC)
	ldx     #>(L01BC)
	jsr     pushax
	jsr     _LISTV_Show
	ldy     #$00
	sta     (sp),y
	.dbg	line, "fdisk.c", 609
	jmp     L0221
	.dbg	line, "fdisk.c", 611
L0200:	lda     #<(L0001+288)
	ldx     #>(L0001+288)
	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 613
L0221:	ldy     #$00
	lda     (sp),y
	cmp     #$FF
	jne     L01E5
	.dbg	line, "fdisk.c", 615
	lda     _dID
	jsr     pusha
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	jsr     _SIO_SetCurDir
	tax
	bne     L0226
	.dbg	line, "fdisk.c", 617
	lda     #<(L0001+294)
	ldx     #>(L0001+294)
L075C:	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 620
L0226:	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 621
	ldy     #$35
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned int DiskCnt (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DiskCnt

	.dbg	line, "fdisk.c", 635
	ldx     #$00
	lda     #$09
	.dbg	line, "fdisk.c", 636
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char DiskItm (unsigned char**, unsigned int)
; ---------------------------------------------------------------

.segment	"BSS"

L0232:
	.res	50,$00

.segment	"CODE1"

.proc	_DiskItm

	.dbg	line, "fdisk.c", 650
	ldy     #$0B
	jsr     subysp
	ldy     #$0C
	lda     (sp),y
	cmp     #$00
	bne     L0236
	dey
	lda     (sp),y
	cmp     #$09
L0236:	jcs     L0234
	.dbg	line, "fdisk.c", 652
	ldy     #$0C
	jsr     ldaxysp
	jsr     incax1
	ldy     #$00
	sta     (sp),y
	.dbg	line, "fdisk.c", 653
	cmp     #$09
	bne     L0239
	.dbg	line, "fdisk.c", 655
	lda     #$01
	sta     (sp),y
	.dbg	line, "fdisk.c", 657
L0239:	lda     #$01
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0A
	jsr     _memset
	.dbg	line, "fdisk.c", 658
	lda     #$01
	jsr     leaasp
	jsr     pushax
	ldy     #$0E
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 659
	ldy     #$0C
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	jeq     L0247
	.dbg	line, "fdisk.c", 661
	lda     #<(L0232)
	ldx     #>(L0232)
	jsr     pushax
	lda     #<(L0001+300)
	ldx     #>(L0001+300)
	jsr     pushax
	.dbg	line, "fdisk.c", 662
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	.dbg	line, "fdisk.c", 663
	lda     #$07
	jsr     leaasp
	jsr     pushax
	.dbg	line, "fdisk.c", 664
	ldy     #$14
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$04
	beq     L0252
	lda     #<(L0001+329)
	ldx     #>(L0001+329)
	jmp     L0254
L0252:	lda     #<(L0001+332)
	ldx     #>(L0001+332)
L0254:	jsr     pushax
	.dbg	line, "fdisk.c", 665
	ldy     #$16
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	ldy     #$0D
	jsr     ldaxidx
	jsr     pushax
	.dbg	line, "fdisk.c", 666
	ldy     #$18
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$40
	beq     L025B
	lda     #<(L0001+335)
	ldx     #>(L0001+335)
	jmp     L025D
L025B:	lda     #<(L0001+340)
	ldx     #>(L0001+340)
L025D:	jsr     pushax
	ldy     #$0E
	.dbg	line, "fdisk.c", 668
	jmp     L075D
	.dbg	line, "fdisk.c", 670
L0247:	lda     #<(L0232)
	ldx     #>(L0232)
	jsr     pushax
	lda     #<(L0001+345)
	ldx     #>(L0001+345)
	jsr     pushax
	.dbg	line, "fdisk.c", 671
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	.dbg	line, "fdisk.c", 672
	lda     #$07
	jsr     leaasp
	jsr     pushax
	ldy     #$08
L075D:	jsr     _sprintf
	.dbg	line, "fdisk.c", 674
	ldy     #$0E
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	lda     #<(L0232)
	ldx     #>(L0232)
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	.dbg	line, "fdisk.c", 675
	ldx     #$00
	tya
	jmp     L0230
	.dbg	line, "fdisk.c", 677
L0234:	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 678
L0230:	ldy     #$0F
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char DiskDummySel (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DiskDummySel

	.dbg	line, "fdisk.c", 688
	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     staxysp
	.dbg	line, "fdisk.c", 689
	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 690
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char OnDiskAction (unsigned int*, unsigned char, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_OnDiskAction

	.dbg	line, "fdisk.c", 703
	ldy     #$11
	jsr     subysp
	ldy     #$12
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
	.dbg	line, "fdisk.c", 705
	ldy     #$15
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	cpx     #$00
	bne     L0273
	cmp     #$09
L0273:	jcs     L02C7
	ldy     #$15
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	jeq     L02C7
	.dbg	line, "fdisk.c", 707
	lda     _fsInfo
	cmp     #$7F
	bne     L0278
	.dbg	line, "fdisk.c", 709
	lda     #<(L0001+356)
	ldx     #>(L0001+356)
	.dbg	line, "fdisk.c", 710
	jmp     L0767
	.dbg	line, "fdisk.c", 712
L0278:	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$17
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 714
	ldy     #$13
	lda     (sp),y
	.dbg	line, "fdisk.c", 734
	cmp     #$52
	beq     L0284
	cmp     #$57
	beq     L028E
	cmp     #$72
	beq     L0284
	cmp     #$77
	beq     L028E
	jmp     L0282
	.dbg	line, "fdisk.c", 718
L0284:	ldy     #$15
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$04
	.dbg	line, "fdisk.c", 720
	jne     L02C7
	.dbg	line, "fdisk.c", 722
	lda     (sp),y
	ora     #$04
	.dbg	line, "fdisk.c", 723
	jmp     L075F
	.dbg	line, "fdisk.c", 726
L028E:	ldy     #$15
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$04
	.dbg	line, "fdisk.c", 728
	jeq     L02C7
	.dbg	line, "fdisk.c", 730
	lda     (sp),y
	and     #$FB
L075F:	sta     (sp),y
	.dbg	line, "fdisk.c", 736
L0282:	lda     _dID
	jsr     pusha
	ldy     #$16
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     incax1
	jsr     pusha
	lda     #$02
	jsr     leaasp
	jsr     pushax
	jsr     _SIO_PutDisk
	tax
	jeq     L0299
	.dbg	line, "fdisk.c", 738
	ldy     #$15
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 739
	ldx     #$00
	txa
L0764:	ldy     #$0F
	jsr     staxysp
	ldy     #$10
	lda     (sp),y
	cmp     #$00
	bne     L02A9
	dey
	lda     (sp),y
	cmp     #$C8
L02A9:	jcs     L02A3
	.dbg	line, "fdisk.c", 741
	ldy     #$10
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	ldy     #$0B
	jsr     ldeaxidx
	jsr     pusheax
	ldy     #$0F
	jsr     ldeaxysp
	jsr     toseqeax
	beq     L02A4
	.dbg	line, "fdisk.c", 743
	ldy     #$10
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 744
	jmp     L02A3
	.dbg	line, "fdisk.c", 739
L02A4:	ldy     #$10
	jsr     ldaxysp
	jsr     incax1
	jmp     L0764
	.dbg	line, "fdisk.c", 747
L02A3:	ldx     #$00
	txa
L0765:	ldy     #$0F
	jsr     staxysp
	ldy     #$10
	lda     (sp),y
	cmp     #$00
	bne     L02BA
	dey
	lda     (sp),y
	cmp     #$09
L02BA:	bcs     L02B4
	.dbg	line, "fdisk.c", 749
	ldy     #$10
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	ldy     #$0B
	jsr     ldeaxidx
	jsr     pusheax
	ldy     #$0F
	jsr     ldeaxysp
	jsr     toseqeax
	beq     L02B5
	.dbg	line, "fdisk.c", 751
	ldy     #$10
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 747
L02B5:	ldy     #$10
	jsr     ldaxysp
	jsr     incax1
	jmp     L0765
	.dbg	line, "fdisk.c", 754
L02B4:	lda     #<(L0001+368)
	ldx     #>(L0001+368)
	jsr     pushax
	lda     #$07
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 756
	lda     #$01
	sta     _upd
	.dbg	line, "fdisk.c", 758
	jmp     L02C7
	.dbg	line, "fdisk.c", 760
L0299:	lda     #<(L0001+371)
	ldx     #>(L0001+371)
L0767:	jsr     pushax
	lda     #$07
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 763
L02C7:	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 764
	ldy     #$16
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void OnDiskFocus (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_OnDiskFocus

	.dbg	line, "fdisk.c", 777
	ldy     #$50
	jsr     subysp
	lda     #<(L0001+377)
	ldx     #>(L0001+377)
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     #$0E
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$12
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 779
	ldy     #$51
	lda     (sp),y
	cmp     #$00
	bne     L02D8
	dey
	lda     (sp),y
	cmp     #$09
L02D8:	jcs     L032C
	.dbg	line, "fdisk.c", 781
	ldy     #$51
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	jeq     L02D9
	.dbg	line, "fdisk.c", 783
	lda     #$02
	jsr     pusha
	lda     #$0F
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 784
	ldy     #$51
	lda     (sp),y
	bne     L076A
	dey
	lda     (sp),y
	cmp     #$08
	beq     L02DF
	.dbg	line, "fdisk.c", 786
L076A:	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+390)
	ldx     #>(L0001+390)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     incax1
	jsr     pushax
	ldy     #$06
	.dbg	line, "fdisk.c", 788
	jmp     L0768
	.dbg	line, "fdisk.c", 790
L02DF:	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+409)
	ldx     #>(L0001+409)
	jsr     pushax
	ldy     #$04
L0768:	jsr     _sprintf
	.dbg	line, "fdisk.c", 792
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 794
	lda     #$02
	jsr     pusha
	lda     #$10
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 795
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+437)
	ldx     #>(L0001+437)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	ldy     #$0B
	jsr     ldeaxidx
	jsr     pusheax
	ldy     #$08
	jsr     _sprintf
	.dbg	line, "fdisk.c", 796
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 798
	lda     #$02
	jsr     pusha
	lda     #$11
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 799
	ldy     #$51
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	cmp     #$7E
	beq     L02FF
	ldy     #$51
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	cmp     #$7E
	bne     L02FD
	.dbg	line, "fdisk.c", 801
L02FF:	lda     _dID
	jsr     pusha
	ldy     #$52
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	ldy     #$0B
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$05
	jsr     leaasp
	jsr     pushax
	.dbg	line, "fdisk.c", 802
	jsr     _SIO_GetLFN
	tax
	beq     L02FD
	.dbg	line, "fdisk.c", 807
	lda     sp
	ldx     sp+1
	jsr     _strlen
	cpx     #$00
	bne     L0310
	cmp     #$25
L0310:	bcc     L031D
	.dbg	line, "fdisk.c", 809
	lda     #$2E
	ldy     #$21
	sta     (sp),y
	.dbg	line, "fdisk.c", 810
	iny
	sta     (sp),y
	.dbg	line, "fdisk.c", 811
	iny
	sta     (sp),y
	.dbg	line, "fdisk.c", 812
	lda     #$00
	iny
	sta     (sp),y
	.dbg	line, "fdisk.c", 815
	jmp     L031D
	.dbg	line, "fdisk.c", 817
L02FD:	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$53
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 818
	lda     #$00
	ldy     #$08
	sta     (sp),y
	.dbg	line, "fdisk.c", 819
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+456)
	ldx     #>(L0001+456)
	jsr     _strcat
	.dbg	line, "fdisk.c", 821
L031D:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 823
	jmp     L032C
	.dbg	line, "fdisk.c", 825
L02D9:	lda     #$01
	jsr     pusha
	lda     #$10
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 826
	ldy     #$51
	lda     (sp),y
	bne     L076B
	dey
	lda     (sp),y
	cmp     #$08
	beq     L0330
	.dbg	line, "fdisk.c", 828
L076B:	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+461)
	ldx     #>(L0001+461)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     incax1
	jsr     pushax
	ldy     #$06
	.dbg	line, "fdisk.c", 830
	jmp     L0769
	.dbg	line, "fdisk.c", 832
L0330:	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+484)
	ldx     #>(L0001+484)
	jsr     pushax
	ldy     #$04
L0769:	jsr     _sprintf
	.dbg	line, "fdisk.c", 834
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 837
L032C:	ldy     #$52
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawDiskList (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawDiskList

	.dbg	line, "fdisk.c", 847
	lda     #$00
	jsr     pusha
	lda     #$13
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 848
	lda     #$01
	jsr     pusha
	lda     #$14
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 849
	lda     #<(L0001+512)
	ldx     #>(L0001+512)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 850
	lda     #$01
	jsr     pusha
	lda     #$15
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 851
	lda     #<(L0001+548)
	ldx     #>(L0001+548)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 852
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 853
	lda     #<(L0001+584)
	ldx     #>(L0001+584)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jmp     _SCR_LineCenter
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void SelectAtariDisk (function returning unsigned char*)
; ---------------------------------------------------------------

.segment	"DATA"

L035A:
	.byte	$00
	.addr	L0001+605
	.byte	$26
	.byte	$00
	.byte	$03
	.byte	$27
	.byte	$0D
	.addr	L0001+617
	.addr	L0001+619
	.addr	_DiskCnt
	.addr	_DiskItm
	.addr	_DiskDummySel
	.addr	_OnDiskAction
	.addr	_OnDiskFocus
	.addr	_DrawDiskList

.segment	"CODE1"

.proc	_SelectAtariDisk

	.dbg	line, "fdisk.c", 870
	ldy     #$01
	jsr     ldaxysp
	sta     L035A+16
	stx     L035A+16+1
	.dbg	line, "fdisk.c", 871
	lda     #<(L035A)
	ldx     #>(L035A)
	jsr     pushax
	jsr     _LISTV_Show
	.dbg	line, "fdisk.c", 872
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void AtrBtnShow (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_AtrBtnShow

	.dbg	line, "fdisk.c", 892
	ldy     #$28
	jsr     subysp
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 893
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+624)
	ldx     #>(L0001+624)
	jsr     pushax
	lda     _lfnON
	beq     L037A
	lda     #<(L0001+655)
	ldx     #>(L0001+655)
	jmp     L037C
L037A:	lda     #<(L0001+659)
	ldx     #>(L0001+659)
L037C:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 894
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 895
	ldy     #$28
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned int AtrCnt (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_AtrCnt

	.dbg	line, "fdisk.c", 905
	lda     _maxFiles
	ldx     _maxFiles+1
	.dbg	line, "fdisk.c", 906
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char AtrItm (unsigned char**, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_AtrItm

	.dbg	line, "fdisk.c", 916
	ldy     #$03
	jsr     pushwysp
	lda     _maxFiles
	ldx     _maxFiles+1
	jsr     tosicmp
	bcs     L0384
	.dbg	line, "fdisk.c", 918
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	ldy     #$00
	jsr     staxspidx
	.dbg	line, "fdisk.c", 919
	ldx     #$00
	lda     #$01
	jmp     incsp4
	.dbg	line, "fdisk.c", 921
L0384:	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 922
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char AtrDummySel (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_AtrDummySel

	.dbg	line, "fdisk.c", 932
	lda     #$00
	sta     _cmpPos
	.dbg	line, "fdisk.c", 933
	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     staxysp
	.dbg	line, "fdisk.c", 934
	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 935
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char AtrDummyAct (unsigned int*, unsigned char, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_AtrDummyAct

	.dbg	line, "fdisk.c", 947
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
	.dbg	line, "fdisk.c", 948
	ldy     #$06
	jsr     ldaxysp
	ldy     #$05
	jsr     staxysp
	.dbg	line, "fdisk.c", 949
	ldy     #$04
	lda     (sp),y
	cmp     #$20
	bne     L0397
	.dbg	line, "fdisk.c", 951
	dey
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	.dbg	line, "fdisk.c", 952
	tax
	lda     _lfnON
	jsr     complax
	sta     _lfnON
	.dbg	line, "fdisk.c", 953
	jsr     _AtrBtnShow
	.dbg	line, "fdisk.c", 955
	jmp     L039E
	.dbg	line, "fdisk.c", 957
L0397:	lda     (sp),y
	cmp     #$61
	bcc     L039F
	sec
	lda     (sp),y
	sbc     #$20
	sta     (sp),y
	.dbg	line, "fdisk.c", 959
L039F:	lda     #<(_cmpBuf)
	ldx     #>(_cmpBuf)
	clc
	adc     _cmpPos
	bcc     L03A5
	inx
L03A5:	sta     ptr1
	stx     ptr1+1
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	.dbg	line, "fdisk.c", 961
	ldx     #$00
	txa
L076E:	ldy     #$00
	jsr     staxysp
	ldy     #$03
	jsr     pushwysp
	lda     _maxFiles
	ldx     _maxFiles+1
	jsr     tosicmp
	jcs     L03A8
	.dbg	line, "fdisk.c", 963
	ldy     #$01
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	sta     ptr1
	txa
	adc     #>(_atrTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	.dbg	line, "fdisk.c", 964
	beq     L03A9
	.dbg	line, "fdisk.c", 965
	ldy     #$01
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	lda     #<(_cmpBuf)
	ldx     #>(_cmpBuf)
	jsr     pushax
	ldx     #$00
	lda     _cmpPos
	jsr     incax1
	jsr     _memcmp
	cpx     #$00
	.dbg	line, "fdisk.c", 966
	bmi     L03A9
	.dbg	line, "fdisk.c", 972
	ldy     #$08
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	jsr     staxspidx
	.dbg	line, "fdisk.c", 973
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	.dbg	line, "fdisk.c", 974
	jmp     L039E
	.dbg	line, "fdisk.c", 961
L03A9:	ldy     #$01
	jsr     ldaxysp
	jsr     incax1
	jmp     L076E
	.dbg	line, "fdisk.c", 977
L03A8:	lda     #$00
	sta     _cmpPos
	.dbg	line, "fdisk.c", 979
L039E:	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 980
	jmp     incsp7
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void OnAtrFocus (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_OnAtrFocus

	.dbg	line, "fdisk.c", 1004
	ldy     #$50
	jsr     subysp
	lda     #<(L0001+663)
	ldx     #>(L0001+663)
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$14
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 1006
	ldy     #$53
	jsr     pushwysp
	lda     _maxFiles
	ldx     _maxFiles+1
	jsr     tosicmp
	jcs     L03D1
	.dbg	line, "fdisk.c", 1008
	ldy     #$51
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	sta     ptr1
	txa
	adc     #>(_atrTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	jeq     L03D1
	.dbg	line, "fdisk.c", 1010
	lda     #$02
	jsr     pusha
	lda     #$13
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1012
	lda     _lfnON
	jeq     L03D8
	.dbg	line, "fdisk.c", 1013
	ldy     #$51
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	sta     ptr1
	txa
	adc     #>(_atrTab)
	sta     ptr1+1
	ldy     #$05
	lda     (ptr1),y
	cmp     #$7E
	beq     L03DB
	ldy     #$51
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	sta     ptr1
	txa
	adc     #>(_atrTab)
	sta     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	cmp     #$7E
	bne     L03D8
	.dbg	line, "fdisk.c", 1015
L03DB:	lda     _dID
	jsr     pusha
	ldy     #$52
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	ldy     #$0B
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$05
	jsr     leaasp
	jsr     pushax
	.dbg	line, "fdisk.c", 1016
	jsr     _SIO_GetLFN
	tax
	beq     L03D8
	.dbg	line, "fdisk.c", 1021
	lda     sp
	ldx     sp+1
	jsr     _strlen
	cpx     #$00
	bne     L03EE
	cmp     #$25
L03EE:	bcc     L03FB
	.dbg	line, "fdisk.c", 1023
	lda     #$2E
	ldy     #$21
	sta     (sp),y
	.dbg	line, "fdisk.c", 1024
	iny
	sta     (sp),y
	.dbg	line, "fdisk.c", 1025
	iny
	sta     (sp),y
	.dbg	line, "fdisk.c", 1026
	lda     #$00
	iny
	sta     (sp),y
	.dbg	line, "fdisk.c", 1029
	jmp     L03FB
	.dbg	line, "fdisk.c", 1031
L03D8:	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$53
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 1032
	lda     #$00
	ldy     #$08
	sta     (sp),y
	.dbg	line, "fdisk.c", 1033
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+680)
	ldx     #>(L0001+680)
	jsr     _strcat
	.dbg	line, "fdisk.c", 1035
L03FB:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1037
	lda     #$02
	jsr     pusha
	lda     #$11
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1038
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+685)
	ldx     #>(L0001+685)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     incax1
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1039
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1040
	lda     #$02
	jsr     pusha
	lda     #$12
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1041
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+695)
	ldx     #>(L0001+695)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	sta     ptr1
	txa
	adc     #>(_atrTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$04
	.dbg	line, "fdisk.c", 1042
	beq     L0420
	lda     #<(L0001+705)
	ldx     #>(L0001+705)
	jmp     L0422
L0420:	lda     #<(L0001+708)
	ldx     #>(L0001+708)
L0422:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1043
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1045
	lda     #$10
	jsr     pusha
	lda     #$11
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1046
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+711)
	ldx     #>(L0001+711)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	ldy     #$0D
	jsr     ldaxidx
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1047
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1048
	lda     #$10
	jsr     pusha
	lda     #$12
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1049
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+731)
	ldx     #>(L0001+731)
	jsr     pushax
	ldy     #$55
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	sta     ptr1
	txa
	adc     #>(_atrTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$40
	.dbg	line, "fdisk.c", 1050
	beq     L043D
	lda     #<(L0001+751)
	ldx     #>(L0001+751)
	jmp     L043F
L043D:	lda     #<(L0001+756)
	ldx     #>(L0001+756)
L043F:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1051
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1055
L03D1:	ldy     #$52
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawAtrList (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawAtrList

	.dbg	line, "fdisk.c", 1065
	lda     #$00
	jsr     pusha
	lda     #$15
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1066
	jmp     _AtrBtnShow
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void SelectAtrFile (function returning unsigned char*, unsigned char*)
; ---------------------------------------------------------------

.segment	"DATA"

L044D:
	.byte	$00
	.addr	L0001+761
	.byte	$08
	.byte	$00
	.byte	$03
	.byte	$27
	.byte	$0F
	.addr	L0001+762
	.addr	L0001+764
	.addr	_AtrCnt
	.addr	_AtrItm
	.addr	_AtrDummySel
	.addr	_AtrDummyAct
	.addr	_OnAtrFocus
	.addr	_DrawAtrList

.segment	"CODE1"

.proc	_SelectAtrFile

	.dbg	line, "fdisk.c", 1084
	lda     #$00
	sta     _cmpPos
	.dbg	line, "fdisk.c", 1085
	sta     _lfnON
	.dbg	line, "fdisk.c", 1086
	ldy     #$03
	jsr     ldaxysp
	sta     L044D+16
	stx     L044D+16+1
	.dbg	line, "fdisk.c", 1087
	ldy     #$01
	jsr     ldaxysp
	sta     L044D+1
	stx     L044D+1+1
	.dbg	line, "fdisk.c", 1088
	lda     #<(L044D)
	ldx     #>(L044D)
	jsr     pushax
	jsr     _LISTV_Show
	.dbg	line, "fdisk.c", 1089
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char ViewParameters (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_ViewParameters

	.dbg	line, "fdisk.c", 1105
	ldy     #$28
	jsr     subysp
	lda     #$00
	jsr     pusha
	lda     #$15
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1106
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1107
	lda     #<(L0001+818)
	ldx     #>(L0001+818)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 1111
	lda     #<(L0001+839)
	ldx     #>(L0001+839)
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$0B
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 1112
	lda     #$06
	jsr     pusha
	lda     #$05
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1113
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+861)
	ldx     #>(L0001+861)
	jsr     pushax
	lda     _drvInfo+9
	and     #$80
	beq     L0483
	lda     #<(L0001+880)
	ldx     #>(L0001+880)
	jmp     L0485
L0483:	lda     #<(L0001+884)
	ldx     #>(L0001+884)
L0485:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1114
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1115
	lda     _drvInfo+9
	and     #$80
	jne     L048A
	.dbg	line, "fdisk.c", 1117
	lda     #$06
	jsr     pusha
	lda     #$06
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1118
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+888)
	ldx     #>(L0001+888)
	jsr     pushax
	ldx     #$00
	lda     _drvInfo+2
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1119
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1120
	lda     #$06
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1121
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+907)
	ldx     #>(L0001+907)
	jsr     pushax
	lda     _drvInfo
	ldx     _drvInfo+1
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1122
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1123
	lda     #$06
	jsr     pusha
	lda     #$08
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1124
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+926)
	ldx     #>(L0001+926)
	jsr     pushax
	lda     _drvInfo+3
	ldx     _drvInfo+3+1
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1125
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1126
	lda     #$06
	jsr     pusha
	lda     #$09
	.dbg	line, "fdisk.c", 1128
	jmp     L076F
	.dbg	line, "fdisk.c", 1130
L048A:	lda     #$06
	jsr     pusha
	lda     #$06
L076F:	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1132
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+945)
	ldx     #>(L0001+945)
	jsr     pushax
	lda     _drvInfo+5+3
	sta     sreg+1
	lda     _drvInfo+5+2
	sta     sreg
	ldx     _drvInfo+5+1
	lda     _drvInfo+5
	jsr     pusheax
	ldy     #$08
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1133
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1135
	lda     #<(L0001+965)
	ldx     #>(L0001+965)
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$14
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 1136
	lda     #$06
	jsr     pusha
	lda     #$0E
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1137
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+986)
	ldx     #>(L0001+986)
	jsr     pushax
	lda     _dID
	cmp     #$01
	bne     L04C7
	lda     #<(L0001+1005)
	ldx     #>(L0001+1005)
	jmp     L04C9
L04C7:	lda     #<(L0001+1012)
	ldx     #>(L0001+1012)
L04C9:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1138
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1139
	lda     #$06
	jsr     pusha
	lda     #$0F
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1140
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1018)
	ldx     #>(L0001+1018)
	jsr     pushax
	ldx     #$00
	lda     _fsInfo+3
	jsr     shrax4
	jsr     pushax
	lda     _fsInfo+3
	ldx     #$00
	and     #$0F
	jsr     pushax
	ldy     #$08
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1141
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1142
	lda     #$06
	jsr     pusha
	lda     #$10
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1143
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1040)
	ldx     #>(L0001+1040)
	jsr     pushax
	lda     _maxFiles
	ldx     _maxFiles+1
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1144
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1146
	lda     #$06
	jsr     pusha
	lda     #$11
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1147
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1059)
	ldx     #>(L0001+1059)
	jsr     pushax
	ldy     #$04
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1148
	lda     _fsInfo
	.dbg	line, "fdisk.c", 1168
	cmp     #$04
	beq     L04EE
	cmp     #$06
	beq     L04F3
	cmp     #$0B
	beq     L04FA
	cmp     #$0C
	beq     L04FA
	cmp     #$0E
	beq     L04F3
	cmp     #$7F
	beq     L0501
	jmp     L0505
	.dbg	line, "fdisk.c", 1151
L04EE:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1076)
	ldx     #>(L0001+1076)
	.dbg	line, "fdisk.c", 1152
	jmp     L0770
	.dbg	line, "fdisk.c", 1156
L04F3:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1088)
	ldx     #>(L0001+1088)
	.dbg	line, "fdisk.c", 1157
	jmp     L0770
	.dbg	line, "fdisk.c", 1160
L04FA:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1098)
	ldx     #>(L0001+1098)
	.dbg	line, "fdisk.c", 1161
	jmp     L0770
	.dbg	line, "fdisk.c", 1163
L0501:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1108)
	ldx     #>(L0001+1108)
	.dbg	line, "fdisk.c", 1164
	jmp     L0770
	.dbg	line, "fdisk.c", 1166
L0505:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1116)
	ldx     #>(L0001+1116)
L0770:	jsr     _strcat
	.dbg	line, "fdisk.c", 1169
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1170
	lda     #$06
	jsr     pusha
	lda     #$12
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1171
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1124)
	ldx     #>(L0001+1124)
	jsr     pushax
	ldx     #$00
	lda     _fsInfo+1
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1172
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$28
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "fdisk.c", 1174
	lda     #<(L0001+1143)
	ldx     #>(L0001+1143)
	jsr     pushax
	jsr     _WaitKey
	.dbg	line, "fdisk.c", 1175
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1176
	ldy     #$28
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char ViewAtrFiles (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_ViewAtrFiles

	.dbg	line, "fdisk.c", 1190
	lda     #<(_AtrDummySel)
	ldx     #>(_AtrDummySel)
	jsr     pushax
	lda     #<(L0001+1145)
	ldx     #>(L0001+1145)
	jsr     pushax
	jsr     _SelectAtrFile
	.dbg	line, "fdisk.c", 1191
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1192
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char AtrSelect (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_AtrSelect

	.dbg	line, "fdisk.c", 1207
	lda     _dID
	jsr     pusha
	ldx     #$00
	lda     _curDisk
	jsr     incax1
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	jsr     _SIO_PutDisk
	tax
	beq     L051F
	.dbg	line, "fdisk.c", 1209
	ldx     #$00
	lda     _curDisk
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "fdisk.c", 1210
	lda     #<(L0001+1162)
	ldx     #>(L0001+1162)
	jsr     pushax
	lda     #$07
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1212
	lda     #$01
	sta     _upd
	.dbg	line, "fdisk.c", 1214
	jmp     L0531
	.dbg	line, "fdisk.c", 1216
L051F:	lda     #<(L0001+1165)
	ldx     #>(L0001+1165)
	jsr     pushax
	lda     #$07
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1219
L0531:	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1220
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char DiskSelect (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DiskSelect

	.dbg	line, "fdisk.c", 1232
	ldy     #$28
	jsr     subysp
	ldy     #$29
	lda     (sp),y
	cmp     #$00
	bne     L053A
	dey
	lda     (sp),y
	cmp     #$09
L053A:	jcs     L0573
	.dbg	line, "fdisk.c", 1234
	ldy     #$29
	jsr     ldaxysp
	sta     _curDisk
	.dbg	line, "fdisk.c", 1238
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	lda     #<(L0001+1171)
	ldx     #>(L0001+1171)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcmp
	cpx     #$00
	bne     L0772
	cmp     #$00
	beq     L053D
	.dbg	line, "fdisk.c", 1239
L0772:	ldy     #$29
	jsr     ldaxysp
	jsr     incax1
	cpx     #$00
	bne     L053D
	cmp     #$09
	.dbg	line, "fdisk.c", 1240
	bne     L053D
	.dbg	line, "fdisk.c", 1242
	lda     #<(L0001+1180)
	ldx     #>(L0001+1180)
	jsr     pushax
	lda     #$09
	.dbg	line, "fdisk.c", 1244
	jmp     L0774
	.dbg	line, "fdisk.c", 1247
L053D:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	sta     ptr1
	txa
	adc     #>(_diskTab)
	sta     ptr1+1
	ldy     #$0E
	lda     (ptr1),y
	and     #$80
	bne     L054E
	.dbg	line, "fdisk.c", 1252
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1193)
	ldx     #>(L0001+1193)
	jsr     pushax
	ldy     #$2D
	jsr     ldaxysp
	jsr     incax1
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1253
	lda     #<(_AtrSelect)
	ldx     #>(_AtrSelect)
	jsr     pushax
	lda     #$02
	jsr     leaasp
	jsr     pushax
	jsr     _SelectAtrFile
	.dbg	line, "fdisk.c", 1255
	jmp     L0573
	.dbg	line, "fdisk.c", 1260
L054E:	lda     #<(L0001+1218)
	ldx     #>(L0001+1218)
	jsr     pushax
	lda     #$07
	jsr     pusha
	jsr     _ShowYesNoButtons
	tax
	jeq     L0573
	.dbg	line, "fdisk.c", 1263
	lda     _dID
	jsr     pusha
	ldy     #$2A
	jsr     ldaxysp
	jsr     incax1
	jsr     pusha
	jsr     _SIO_DiskOff
	tax
	beq     L055F
	.dbg	line, "fdisk.c", 1265
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0F
	jsr     _memset
	.dbg	line, "fdisk.c", 1266
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_diskTab)
	tay
	txa
	adc     #>(_diskTab)
	tax
	tya
	jsr     pushax
	lda     #<(L0001+1229)
	ldx     #>(L0001+1229)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 1267
	lda     #<(L0001+1238)
	ldx     #>(L0001+1238)
	jsr     pushax
	lda     #$07
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1269
	lda     #$01
	sta     _upd
	.dbg	line, "fdisk.c", 1271
	jmp     L0573
	.dbg	line, "fdisk.c", 1273
L055F:	lda     #<(L0001+1241)
	ldx     #>(L0001+1241)
	jsr     pushax
	lda     #$07
L0774:	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1278
L0573:	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 1279
	ldy     #$2A
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char EditAtariDisks (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_EditAtariDisks

	.dbg	line, "fdisk.c", 1289
	lda     #<(_DiskSelect)
	ldx     #>(_DiskSelect)
	jsr     pushax
	jsr     _SelectAtariDisk
	.dbg	line, "fdisk.c", 1290
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1291
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawMainMenu (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawMainMenu

	.dbg	line, "fdisk.c", 1334
	ldy     #$34
	jsr     subysp
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$11
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1336
	lda     #$00
	jsr     pusha
	lda     #$12
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$14
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1337
	lda     #$03
	jsr     pusha
	lda     #$13
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1338
	lda     #$28
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0C
	jsr     _memset
	.dbg	line, "fdisk.c", 1339
	lda     #$28
	jsr     leaasp
	jsr     pushax
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcpy
	.dbg	line, "fdisk.c", 1340
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0001+1268)
	ldx     #>(L0001+1268)
	jsr     pushax
	lda     #$2C
	jsr     leaasp
	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	.dbg	line, "fdisk.c", 1341
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 1343
	lda     #$00
	jsr     pusha
	lda     #$15
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1344
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1345
	lda     #<(L0001+1292)
	ldx     #>(L0001+1292)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 1346
	ldy     #$34
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void MainMenu (void)
; ---------------------------------------------------------------

.segment	"DATA"

L05BF:
	.byte	$01
	.addr	L0001+1306
	.addr	L0001+1327
	.addr	_ViewParameters
	.byte	$01
	.addr	L0001+1330
	.addr	L0001+1353
	.addr	_ViewDirectories
	.byte	$01
	.addr	L0001+1356
	.addr	L0001+1376
	.addr	_ViewAtrFiles
	.byte	$01
	.addr	L0001+1379
	.addr	L0001+1396
	.addr	_EditAtariDisks
	.byte	$01
	.addr	L0001+1399
	.addr	L0001+1423
	.addr	_SaveConfig
	.byte	$02
	.addr	L0001+1426
	.addr	L0001+1436
	.word	$0000
	.byte	$00
	.addr	L0001+1438
	.addr	L0001+1439
	.word	$0000
L05DC:
	.byte	$01
	.addr	L0001+1440
	.byte	$06
	.byte	$06
	.byte	$20
	.byte	$0D
	.addr	L05BF
	.addr	L0001+1450
	.addr	_DrawMainMenu

.segment	"CODE1"

.proc	_MainMenu

	.dbg	line, "fdisk.c", 1371
	lda     #<(L05DC)
	ldx     #>(L05DC)
	jsr     pushax
	jmp     _MENU_Show
	.dbg	line

.endproc

; ---------------------------------------------------------------
; signed short CmpATR (signed short, signed short)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_CmpATR

	.dbg	line, "fdisk.c", 1387
	ldy     #$03
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$0F
	jsr     tosmula0
	clc
	adc     #<(_atrTab)
	tay
	txa
	adc     #>(_atrTab)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     _memcmp
	.dbg	line, "fdisk.c", 1388
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void SwpATR (signed short, signed short)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_SwpATR

	.dbg	line, "fdisk.c", 1400
	jsr     decsp1
	ldy     #$04
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     (sp),y
	.dbg	line, "fdisk.c", 1401
	ldy     #$04
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	jsr     pushax
	ldy     #$04
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	jsr     staxspidx
	.dbg	line, "fdisk.c", 1402
	ldy     #$02
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_atrInd)
	tay
	txa
	adc     #>(_atrInd)
	tax
	tya
	sta     sreg
	stx     sreg+1
	ldy     #$00
	lda     (sp),y
	sta     (sreg),y
	iny
	lda     #$00
	sta     (sreg),y
	.dbg	line, "fdisk.c", 1403
	jmp     incsp5
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char InitConfig (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_InitConfig

	.dbg	line, "fdisk.c", 1416
	jsr     decsp5
	lda     #<(_drvInfo)
	ldx     #>(_drvInfo)
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$0A
	jsr     _memset
	.dbg	line, "fdisk.c", 1417
	lda     #<(_fsInfo)
	ldx     #>(_fsInfo)
	jsr     pushax
	ldx     #$00
	txa
	jsr     pushax
	lda     #$04
	jsr     _memset
	.dbg	line, "fdisk.c", 1420
	lda     #$0A
	jsr     pusha
	lda     #$07
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1421
	lda     #<(L0001+1451)
	ldx     #>(L0001+1451)
	jsr     pushax
	lda     #$13
	jsr     pusha
	jsr     _SCR_LineCenterClr
	.dbg	line, "fdisk.c", 1422
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$0B
	jsr     pusha
	lda     #$09
	jsr     pusha
	lda     #$0F
	jsr     pusha
	ldx     #$00
	lda     #$02
	jsr     pushax
	jsr     _SCR_ProgressShow
	.dbg	line, "fdisk.c", 1424
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #<(_fsInfo)
	ldx     #>(_fsInfo)
	jsr     pushax
	jsr     _SIO_GetFSInfo
	tax
	.dbg	line, "fdisk.c", 1425
	jeq     incsp6
	.dbg	line, "fdisk.c", 1426
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	jsr     _SCR_ProgressUpdate
	.dbg	line, "fdisk.c", 1428
	lda     _fsInfo+3
	cmp     #$44
	beq     L0619
	.dbg	line, "fdisk.c", 1430
	lda     #<(L0001+1465)
	ldx     #>(L0001+1465)
	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1431
	ldx     #$00
	txa
	jmp     incsp6
	.dbg	line, "fdisk.c", 1434
L0619:	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #<(_drvInfo)
	ldx     #>(_drvInfo)
	jsr     pushax
	jsr     _SIO_GetDriveInfo
	tax
	.dbg	line, "fdisk.c", 1435
	jeq     incsp6
	.dbg	line, "fdisk.c", 1436
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	jsr     _SCR_ProgressUpdate
	.dbg	line, "fdisk.c", 1438
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1439
	jmp     incsp6
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawLoadScreen (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawLoadScreen

	.dbg	line, "fdisk.c", 1557
	lda     #$00
	sta     _upd
	.dbg	line, "fdisk.c", 1559
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$14
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1560
	lda     #<(L0001+1532)
	ldx     #>(L0001+1532)
	jsr     pushax
	lda     #$09
	jsr     pusha
	lda     #$05
	jsr     pusha
	lda     #$1D
	jsr     pusha
	lda     #$0C
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "fdisk.c", 1562
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	jsr     _InitConfig
	tax
	beq     L06AE
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	jsr     _InitData
	tax
	beq     L06AE
	.dbg	line, "fdisk.c", 1565
	ldy     #$00
	lda     (sp),y
	jsr     pusha
	lda     #<(_actDir)
	ldx     #>(_actDir)
	jsr     pushax
	jsr     _SIO_GetCurDir
	tax
	beq     L06B8
	.dbg	line, "fdisk.c", 1567
	lda     _actDir+14
	and     #$02
	beq     L06B8
	.dbg	line, "fdisk.c", 1569
	lda     #<(L0001+1545)
	ldx     #>(L0001+1545)
	jsr     pushax
	lda     #$11
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1571
	jsr     _MainMenu
	.dbg	line, "fdisk.c", 1575
L06B8:	lda     _upd
	jeq     incsp1
	lda     _fsInfo
	cmp     #$7F
	jeq     incsp1
	.dbg	line, "fdisk.c", 1577
	lda     #<(L0001+1548)
	ldx     #>(L0001+1548)
	jsr     pushax
	lda     #$0E
	jsr     pusha
	jsr     _ShowYesNoButtons
	tax
	jeq     incsp1
	.dbg	line, "fdisk.c", 1579
	jsr     _SaveConfig
	.dbg	line, "fdisk.c", 1583
	jmp     incsp1
	.dbg	line, "fdisk.c", 1585
L06AE:	lda     #<(L0001+1562)
	ldx     #>(L0001+1562)
	jsr     pushax
	lda     #$09
	jsr     pusha
	jsr     _ShowCnfButton
	.dbg	line, "fdisk.c", 1587
	jmp     incsp1
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char LoadMasterData (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_LoadMasterData

	.dbg	line, "fdisk.c", 1597
	lda     #$01
	sta     _dID
	.dbg	line, "fdisk.c", 1598
	lda     _dID
	jsr     pusha
	jsr     _DrawLoadScreen
	.dbg	line, "fdisk.c", 1599
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1600
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char LoadSlaveData (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_LoadSlaveData

	.dbg	line, "fdisk.c", 1610
	lda     #$02
	sta     _dID
	.dbg	line, "fdisk.c", 1611
	lda     _dID
	jsr     pusha
	jsr     _DrawLoadScreen
	.dbg	line, "fdisk.c", 1612
	ldx     #$00
	lda     #$01
	.dbg	line, "fdisk.c", 1613
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawMainWindows (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawMainWindows

	.dbg	line, "fdisk.c", 1628
	lda     #$00
	jsr     pusha
	lda     #$15
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1629
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1642
	lda     #<(L0001+1568)
	ldx     #>(L0001+1568)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 1646
	lda     #$00
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1647
	lda     #$01
	jsr     pusha
	lda     #$01
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1648
	ldy     #$00
	lda     (sp),y
	beq     L06EE
	.dbg	line, "fdisk.c", 1650
	lda     #<(L0001+1600)
	ldx     #>(L0001+1600)
	.dbg	line, "fdisk.c", 1652
	jmp     L0778
	.dbg	line, "fdisk.c", 1654
L06EE:	lda     #<(L0001+1633)
	ldx     #>(L0001+1633)
L0778:	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 1656
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$27
	jsr     pusha
	lda     #$14
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1657
	jmp     incsp1
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void DrawMainScreen (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_DrawMainScreen

	.dbg	line, "fdisk.c", 1667
	lda     #$01
	jsr     pusha
	jmp     _DrawMainWindows
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void MainScreen (void)
; ---------------------------------------------------------------

.segment	"DATA"

L0701:
	.byte	$01
	.addr	L0001+1656
	.addr	L0001+1675
	.addr	_LoadMasterData
	.byte	$01
	.addr	L0001+1678
	.addr	L0001+1696
	.addr	_LoadSlaveData
	.byte	$02
	.addr	L0001+1699
	.addr	L0001+1709
	.word	$0000
	.byte	$00
	.addr	L0001+1711
	.addr	L0001+1712
	.word	$0000
L0712:
	.byte	$01
	.addr	L0001+1713
	.byte	$09
	.byte	$08
	.byte	$1D
	.byte	$0C
	.addr	L0701
	.addr	L0001+1730
	.addr	_DrawMainScreen

.segment	"CODE1"

.proc	_MainScreen

	.dbg	line, "fdisk.c", 1695
	lda     #<(L0712)
	ldx     #>(L0712)
	jsr     pushax
	jmp     _MENU_Show
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned int main (void)
; ---------------------------------------------------------------

.segment	"CODE1"

.proc	_main

	.dbg	line, "fdisk.c", 1714
	jsr     _SCR_Init
	.dbg	line, "fdisk.c", 1721
	lda     #$00
	jsr     pusha
	jsr     _DrawMainWindows
	.dbg	line, "fdisk.c", 1722
	lda     #<(L0001+1731)
	ldx     #>(L0001+1731)
	jsr     pushax
	.dbg	line, "fdisk.c", 1723
	lda     #<(L0001+1750)
	ldx     #>(L0001+1750)
	jsr     pushax
	.dbg	line, "fdisk.c", 1724
	lda     #<(L0001+1773)
	ldx     #>(L0001+1773)
	jsr     pushax
	.dbg	line, "fdisk.c", 1725
	lda     #<(L0001+1796)
	ldx     #>(L0001+1796)
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	.dbg	line, "fdisk.c", 1726
	jsr     _WaitKeyFor
	.dbg	line, "fdisk.c", 1745
	cmp     #$1B
	beq     L072A
	cmp     #$20
	beq     L0728
	jmp     L0728
	.dbg	line, "fdisk.c", 1730
L072A:	jsr     _MainScreen
	.dbg	line, "fdisk.c", 1732
	jsr     _DrawMainScreen
	.dbg	line, "fdisk.c", 1733
	lda     #<(L0001+1799)
	ldx     #>(L0001+1799)
	jsr     pushax
	lda     #$0A
	jsr     pusha
	jsr     _ShowYesNoButtons
	tax
	bne     L0728
	.dbg	line, "fdisk.c", 1735
	lda     #$07
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$1F
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "fdisk.c", 1736
	lda     #$01
	jsr     pusha
	lda     #$0B
	jsr     _gotoxy
	.dbg	line, "fdisk.c", 1737
	lda     #<(L0001+1815)
	ldx     #>(L0001+1815)
	jsr     pushax
	lda     #$26
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "fdisk.c", 1738
	jsr     _CardWait
	.dbg	line, "fdisk.c", 1748
L0728:	jsr     _SCR_DeInit
	.dbg	line, "fdisk.c", 1750
	ldx     #$00
	txa
	.dbg	line, "fdisk.c", 1751
	rts
	.dbg	line

.endproc

