;
; File generated by cc65 v 2.8.0
;
	.fopt		compiler,"cc65 v 2.8.0"
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "listv.c", 8252, 1279048568
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdlib.h", 4033, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stddef.h", 2865, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdio.h", 5323, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdarg.h", 3007, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/string.h", 4335, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/conio.h", 7309, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/atari.h", 9513, 1030607464
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_gtia.h", 5733, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pbi.h", 3057, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pokey.h", 4268, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pia.h", 2655, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_antic.h", 3412, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/ctype.h", 7873, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/joystick.h", 3317, 1018643664
	.dbg		file, "plat.h", 1225, 1279048568
	.dbg		file, "type.h", 1140, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/cfg.h", 800, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/ptable.h", 2129, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/direntry.h", 4014, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/iso.h", 8718, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/idestruc.h", 1307, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/fatstruc.h", 3099, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/siocmds.h", 2388, 1279048570
	.dbg		file, "keys.h", 865, 1279048568
	.dbg		file, "siosrv.h", 1744, 1279048568
	.dbg		file, "screen.h", 1856, 1279048568
	.dbg		file, "menu.h", 1328, 1279048568
	.dbg		file, "listv.h", 1458, 1279048568
	.dbg		file, "qsort.h", 847, 1279048568
	.import		_strchr
	.import		_memset
	.import		_kbhit
	.import		_gotoxy
	.import		_cgetc
	.import		_readjoy
	.import		_SCR_DrawWindow
	.import		_SCR_DrawLine
	.export		_LISTV_Show
	.export		_LISTV_ReFresh

; ---------------------------------------------------------------
; unsigned char LISTV_Show (struct $anon-struct-0020*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_LISTV_Show

	.dbg	line, "listv.c", 249
	ldx     #$00
	txa
	jsr     pushax
	.dbg	line, "listv.c", 250
	txa
	jsr     pushax
	.dbg	line, "listv.c", 251
	txa
	jsr     pushax
	.dbg	line, "listv.c", 252
	lda     #$FF
	jsr     pusha
	.dbg	line, "listv.c", 257
	jsr     decsp4
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$0D
	jsr     ldaxidx
	stx     tmp1
	ora     tmp1
	beq     L01E4
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	stx     tmp1
	ora     tmp1
	beq     L01E4
	lda     #$00
	jmp     L01E3
	.dbg	line, "listv.c", 259
L01E4:	tax
	lda     #$FF
	jmp     L01DE
	.dbg	line, "listv.c", 261
L01E3:	tax
	ldy     #$09
	jsr     staxysp
	.dbg	line, "listv.c", 262
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$0D
	jsr     ldaxidx
	ldy     #$00
	jsr     callax
	ldy     #$07
	jsr     staxysp
	.dbg	line, "listv.c", 263
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$06
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0E
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tossubax
	jsr     decax1
	ldy     #$03
	sta     (sp),y
	.dbg	line, "listv.c", 264
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0E
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tossubax
	jsr     decax1
	ldy     #$02
	sta     (sp),y
	.dbg	line, "listv.c", 265
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pushax
	ldy     #$10
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tosudivax
	jsr     tosumulax
	ldy     #$05
	jsr     staxysp
	.dbg	line, "listv.c", 267
L0266:	ldy     #$0E
	jsr     pushwysp
	jsr     _LISTV_ReFresh
	.dbg	line, "listv.c", 271
L01F7:	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$0E
	jsr     pushwysp
	ldy     #$0A
	jsr     ldaxysp
	jsr     tosdivax
	jsr     tosicmp
	beq     L01F8
	.dbg	line, "listv.c", 273
	ldy     #$0E
	jsr     pushwysp
	ldy     #$0E
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _LISTV_Draw
	.dbg	line, "listv.c", 274
	ldy     #$0C
	jsr     pushwysp
	ldy     #$08
	jsr     ldaxysp
	jsr     tosdivax
	ldy     #$04
	sta     (sp),y
	.dbg	line, "listv.c", 276
	jmp     L0203
	.dbg	line, "listv.c", 278
L01F8:	ldy     #$0E
	jsr     pushwysp
	ldy     #$0E
	jsr     pushwysp
	ldy     #$0C
	jsr     pushwysp
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _LISTV_Draw
	.dbg	line, "listv.c", 280
L0203:	ldy     #$0C
	jsr     ldaxysp
	ldy     #$14
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L020B
	.dbg	line, "listv.c", 282
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$15
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0E
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	ldy     #$02
	jsr     callax
	jsr     incsp2
	.dbg	line, "listv.c", 284
L020B:	ldy     #$0E
	jsr     pushwysp
	lda     #$03
	jsr     leaasp
	jsr     pushax
	jsr     _LISTV_WaitKey
	.dbg	line, "listv.c", 337
	cmp     #$1C
	beq     L0217
	cmp     #$1D
	beq     L0222
	cmp     #$1E
	beq     L022E
	cmp     #$1F
	jeq     L0237
	cmp     #$9B
	jeq     L0254
	cmp     #$FE
	jeq     L0242
	cmp     #$FF
	jne     L01F7
	.dbg	line, "listv.c", 287
	ldx     #$00
	jmp     L01DE
	.dbg	line, "listv.c", 289
L0217:	ldy     #$0A
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bmi     L021B
	ldy     #$0A
	jsr     ldaxysp
	jsr     decax1
	jmp     L021E
L021B:	ldy     #$0A
	jsr     ldaxysp
L021E:	ldy     #$09
	jsr     staxysp
	.dbg	line, "listv.c", 290
	jmp     L01F7
	.dbg	line, "listv.c", 292
L0222:	ldy     #$0C
	jsr     pushwysp
	ldy     #$0A
	jsr     ldaxysp
	jsr     decax1
	jsr     tosicmp
	bpl     L0227
	ldy     #$0A
	jsr     ldaxysp
	jsr     incax1
	jmp     L022A
L0227:	ldy     #$0A
	jsr     ldaxysp
L022A:	ldy     #$09
	jsr     staxysp
	.dbg	line, "listv.c", 293
	jmp     L01F7
	.dbg	line, "listv.c", 295
L022E:	ldy     #$0C
	jsr     pushwysp
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosicmp
	bcc     L022F
	.dbg	line, "listv.c", 297
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$09
	jsr     subeqysp
	.dbg	line, "listv.c", 299
	jmp     L01F7
	.dbg	line, "listv.c", 301
L022F:	ldx     #$00
	txa
	ldy     #$09
	jsr     staxysp
	.dbg	line, "listv.c", 303
	jmp     L01F7
	.dbg	line, "listv.c", 305
L0237:	ldy     #$0A
	jsr     ldaxysp
	ldy     #$02
	clc
	adc     (sp),y
	bcc     L0261
	inx
L0261:	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	jsr     decax1
	jsr     tosicmp
	beq     L0262
	bcs     L0238
	.dbg	line, "listv.c", 307
L0262:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$09
	jsr     addeqysp
	.dbg	line, "listv.c", 309
	jmp     L01F7
	.dbg	line, "listv.c", 311
L0238:	ldy     #$08
	jsr     ldaxysp
	jsr     decax1
	ldy     #$09
	jsr     staxysp
	.dbg	line, "listv.c", 313
	jmp     L01F7
	.dbg	line, "listv.c", 315
L0242:	ldy     #$0C
	jsr     ldaxysp
	ldy     #$12
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L0245
	.dbg	line, "listv.c", 316
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$13
	jsr     ldaxidx
	jsr     pushax
	lda     #$0B
	jsr     leaasp
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     #$05
	jsr     leaasp
	jsr     pushax
	ldy     #$06
	jsr     ldaxysp
	ldy     #$05
	jsr     callax
	jsr     incsp2
	tax
	beq     L0245
	.dbg	line, "listv.c", 318
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jmp     L01DE
	.dbg	line, "listv.c", 320
L0245:	tay
	lda     (sp),y
	bne     L024C
	ldy     #$04
	tax
	lda     (sp),y
	jsr     pushax
	ldy     #$0E
	jsr     pushwysp
	ldy     #$0A
	jsr     ldaxysp
	jsr     tosdivax
	jsr     tosicmp
	jeq     L01F7
	.dbg	line, "listv.c", 322
L024C:	lda     #$FF
	ldy     #$04
	sta     (sp),y
	.dbg	line, "listv.c", 325
	jmp     L0266
	.dbg	line, "listv.c", 327
L0254:	ldy     #$0C
	jsr     ldaxysp
	ldy     #$10
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L0257
	.dbg	line, "listv.c", 328
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$11
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0E
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	ldy     #$02
	jsr     callax
	jsr     incsp2
	tax
	beq     L0257
	.dbg	line, "listv.c", 330
	ldx     #$00
	lda     #$9B
	jmp     L01DE
	.dbg	line, "listv.c", 332
L0257:	lda     #$FF
	ldy     #$04
	sta     (sp),y
	.dbg	line, "listv.c", 334
	jmp     L0266
	.dbg	line, "listv.c", 340
L01DE:	ldy     #$0D
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void LISTV_Delay (unsigned long)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_LISTV_Delay

	.dbg	line, "listv.c", 46
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void LISTV_DrawItem (unsigned char*, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_LISTV_DrawItem

	.dbg	line, "listv.c", 56
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	.dbg	line, "listv.c", 58
	ldy     #$29
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	.dbg	line, "listv.c", 60
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldy     #$2E
	lda     (sp),y
	cmp     #$01
	bne     L00DE
	ldx     #$00
	lda     #$A0
	jmp     L00E0
L00DE:	ldx     #$00
	lda     #$20
L00E0:	jsr     pushax
	lda     #$28
	jsr     _memset
	.dbg	line, "listv.c", 61
L00E4:	ldy     #$2F
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jeq     L00E5
	ldy     #$2B
	lda     (sp),y
	pha
	sec
	sbc     #$01
	sta     (sp),y
	pla
	tax
	beq     L00E5
	.dbg	line, "listv.c", 63
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$2E
	lda     (sp),y
	cmp     #$01
	bne     L00EC
	ldy     #$31
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$33
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$1B
	bne     L00EF
	ldx     #$00
	txa
	jmp     L00F1
L00EF:	ldx     #$00
	lda     #$80
L00F1:	jsr     tosaddax
	jmp     L00F4
L00EC:	ldy     #$31
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
L00F4:	ldy     #$00
	jsr     staspidx
	.dbg	line, "listv.c", 64
	ldy     #$2F
	jsr     ldaxysp
	jsr     incax1
	ldy     #$2E
	jsr     staxysp
	.dbg	line, "listv.c", 65
	jmp     L00E4
	.dbg	line, "listv.c", 66
L00E5:	lda     #$02
	jsr     leaasp
	ldy     #$2D
	clc
	adc     (sp),y
	bcc     L00FA
	inx
L00FA:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	.dbg	line, "listv.c", 67
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldy     #$2F
	lda     (sp),y
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "listv.c", 68
	ldy     #$30
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void LISTV_DrawEmptyItem (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_LISTV_DrawEmptyItem

	.dbg	line, "listv.c", 80
	ldy     #$29
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     pushax
	lda     #$28
	jsr     _memset
	.dbg	line, "listv.c", 81
	lda     sp
	ldx     sp+1
	ldy     #$29
	clc
	adc     (sp),y
	bcc     L0107
	inx
L0107:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	.dbg	line, "listv.c", 82
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$2B
	lda     (sp),y
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "listv.c", 83
	ldy     #$2A
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void LISTV_Draw (struct $anon-struct-0020*, signed short, unsigned int, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"DATA"

L010D:
	.byte	$00

.segment	"CODE2"

.proc	_LISTV_Draw

	.dbg	line, "listv.c", 99
	jsr     decsp7
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tosudivax
	ldy     #$02
	sta     (sp),y
	.dbg	line, "listv.c", 100
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pushax
	ldy     #$13
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tosumulax
	jsr     tossubax
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     decax1
	jsr     tosudivax
	ldy     #$00
	sta     (sp),y
	.dbg	line, "listv.c", 101
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosudivax
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosumulax
	ldy     #$03
	jsr     staxysp
	.dbg	line, "listv.c", 103
	ldy     #$07
	lda     (sp),y
	jeq     L011A
	.dbg	line, "listv.c", 105
	ldy     #$0D
	jsr     ldaxysp
	sta     L010D
	.dbg	line, "listv.c", 107
	lda     #$00
L026D:	ldy     #$02
	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	ldy     #$06
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tosicmp
	jcs     L0146
	.dbg	line, "listv.c", 109
	lda     #$00
	ldy     #$01
	sta     (sp),y
L0129:	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$0A
	lda     (sp),y
	jsr     tosicmp
	jcs     L0120
	.dbg	line, "listv.c", 111
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	ldy     #$02
	clc
	adc     (sp),y
	bcc     L0267
	inx
L0267:	jsr     incax1
	jsr     pusha
	ldy     #$10
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	ldy     #$02
	clc
	adc     (sp),y
	bcc     L0268
	inx
L0268:	jsr     incax1
	jsr     _gotoxy
	.dbg	line, "listv.c", 112
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	lda     #$07
	jsr     leaasp
	jsr     pushax
	ldy     #$0A
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	ldy     #$04
	jsr     callax
	jsr     incsp2
	tax
	beq     L0134
	.dbg	line, "listv.c", 114
	ldy     #$08
	jsr     pushwysp
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$09
	jsr     pushwysp
	ldy     #$12
	jsr     ldaxysp
	jsr     tosicmp
	bne     L013D
	lda     #$01
	jmp     L013F
L013D:	lda     #$00
L013F:	jsr     pusha
	jsr     _LISTV_DrawItem
	.dbg	line, "listv.c", 116
	jmp     L0142
	.dbg	line, "listv.c", 118
L0134:	ldy     #$0F
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	jsr     _LISTV_DrawEmptyItem
	.dbg	line, "listv.c", 120
L0142:	ldy     #$04
	jsr     ldaxysp
	jsr     incax1
	ldy     #$03
	jsr     staxysp
	.dbg	line, "listv.c", 109
	ldy     #$01
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	jmp     L0129
	.dbg	line, "listv.c", 107
L0120:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tosaddax
	ldy     #$00
	clc
	adc     (sp),y
	jmp     L026D
	.dbg	line, "listv.c", 126
L011A:	tax
	lda     L010D
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosumodax
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (sp),y
	jsr     tosudivax
	ldy     #$03
	jsr     staxysp
	.dbg	line, "listv.c", 127
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$08
	jsr     pushwysp
	ldy     #$13
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	iny
	clc
	adc     (sp),y
	bcc     L026A
	inx
L026A:	jsr     tosumulax
	jsr     tosaddax
	jsr     incax1
	ldy     #$02
	sta     (sp),y
	.dbg	line, "listv.c", 128
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	lda     L010D
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tosumodax
	jsr     pushax
	ldy     #$0C
	ldx     #$00
	lda     (sp),y
	jsr     tosumodax
	jsr     tosaddax
	jsr     incax1
	ldy     #$01
	sta     (sp),y
	.dbg	line, "listv.c", 129
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _gotoxy
	.dbg	line, "listv.c", 130
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	lda     #$07
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     L010D
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$04
	jsr     callax
	jsr     incsp2
	tax
	beq     L0155
	.dbg	line, "listv.c", 132
	ldy     #$08
	jsr     pushwysp
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _LISTV_DrawItem
	.dbg	line, "listv.c", 135
L0155:	ldy     #$0F
	jsr     pushwysp
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosumodax
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (sp),y
	jsr     tosudivax
	ldy     #$03
	jsr     staxysp
	.dbg	line, "listv.c", 136
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$08
	jsr     pushwysp
	ldy     #$13
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	iny
	clc
	adc     (sp),y
	bcc     L026B
	inx
L026B:	jsr     tosumulax
	jsr     tosaddax
	jsr     incax1
	ldy     #$02
	sta     (sp),y
	.dbg	line, "listv.c", 137
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$11
	jsr     pushwysp
	ldy     #$0F
	jsr     ldaxysp
	jsr     tosumodax
	jsr     pushax
	ldy     #$0C
	ldx     #$00
	lda     (sp),y
	jsr     tosumodax
	jsr     tosaddax
	jsr     incax1
	ldy     #$01
	sta     (sp),y
	.dbg	line, "listv.c", 138
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _gotoxy
	.dbg	line, "listv.c", 139
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	lda     #$07
	jsr     leaasp
	jsr     pushax
	ldy     #$13
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	ldy     #$04
	jsr     callax
	jsr     incsp2
	tax
	beq     L016B
	.dbg	line, "listv.c", 141
	ldy     #$08
	jsr     pushwysp
	ldy     #$11
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _LISTV_DrawItem
	.dbg	line, "listv.c", 144
L016B:	ldy     #$0D
	jsr     ldaxysp
	sta     L010D
	.dbg	line, "listv.c", 146
L0146:	ldy     #$10
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char LISTV_WaitKey (struct $anon-struct-0020*, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_LISTV_WaitKey

	.dbg	line, "listv.c", 158
	jsr     decsp1
	.dbg	line, "listv.c", 160
L0179:	lda     #$FF
	ldy     #$00
	sta     (sp),y
	.dbg	line, "listv.c", 161
	jsr     _kbhit
	tax
	beq     L017C
	.dbg	line, "listv.c", 163
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
	.dbg	line, "listv.c", 166
L017C:	lda     #$00
	jsr     _readjoy
	.dbg	line, "listv.c", 185
	cpx     #$00
	bne     L0182
	cmp     #$01
	beq     L0184
	cmp     #$02
	beq     L0188
	cmp     #$04
	beq     L018C
	cmp     #$08
	beq     L0190
	cmp     #$10
	beq     L0194
	jmp     L0182
	.dbg	line, "listv.c", 169
L0184:	lda     #$1C
	.dbg	line, "listv.c", 170
	jmp     L026F
	.dbg	line, "listv.c", 172
L0188:	lda     #$1D
	.dbg	line, "listv.c", 173
	jmp     L026F
	.dbg	line, "listv.c", 175
L018C:	lda     #$1E
	.dbg	line, "listv.c", 176
	jmp     L026F
	.dbg	line, "listv.c", 178
L0190:	lda     #$1F
	.dbg	line, "listv.c", 179
	jmp     L026F
	.dbg	line, "listv.c", 181
L0194:	lda     #$9B
L026F:	ldy     #$00
	sta     (sp),y
	.dbg	line, "listv.c", 186
L0182:	ldy     #$00
	lda     (sp),y
	.dbg	line, "listv.c", 222
	beq     L0179
	cmp     #$1C
	beq     L01A4
	cmp     #$1D
	beq     L01AD
	cmp     #$1E
	beq     L01B6
	cmp     #$1F
	jeq     L01BF
	cmp     #$2A
	jeq     L01BF
	cmp     #$2B
	beq     L01B6
	cmp     #$2D
	beq     L01A4
	cmp     #$3D
	beq     L01AD
	cmp     #$9B
	beq     L019F
	cmp     #$9C
	beq     L01A4
	cmp     #$9D
	beq     L01AD
	cmp     #$9E
	beq     L01B6
	cmp     #$9F
	beq     L01BF
	cmp     #$FF
	jeq     L0179
	jmp     L01C7
	.dbg	line, "listv.c", 192
L019F:	ldx     #$01
	tya
	sta     sreg
	sta     sreg+1
	lda     #$F4
	jsr     pusheax
	jsr     _LISTV_Delay
	.dbg	line, "listv.c", 193
	ldx     #$00
	lda     #$9B
	jmp     incsp5
	.dbg	line, "listv.c", 197
L01A4:	ldx     #$01
	tya
	sta     sreg
	sta     sreg+1
	lda     #$F4
	jsr     pusheax
	jsr     _LISTV_Delay
	.dbg	line, "listv.c", 198
	ldx     #$00
	lda     #$1C
	jmp     incsp5
	.dbg	line, "listv.c", 202
L01AD:	ldx     #$01
	tya
	sta     sreg
	sta     sreg+1
	lda     #$F4
	jsr     pusheax
	jsr     _LISTV_Delay
	.dbg	line, "listv.c", 203
	ldx     #$00
	lda     #$1D
	jmp     incsp5
	.dbg	line, "listv.c", 207
L01B6:	ldx     #$01
	tya
	sta     sreg
	sta     sreg+1
	lda     #$F4
	jsr     pusheax
	jsr     _LISTV_Delay
	.dbg	line, "listv.c", 208
	ldx     #$00
	lda     #$1E
	jmp     incsp5
	.dbg	line, "listv.c", 212
L01BF:	ldx     #$01
	tya
	sta     sreg
	sta     sreg+1
	lda     #$F4
	jsr     pusheax
	jsr     _LISTV_Delay
	.dbg	line, "listv.c", 213
	ldx     #$00
	lda     #$1F
	jmp     incsp5
	.dbg	line, "listv.c", 215
L01C7:	ldy     #$04
	jsr     ldaxysp
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	beq     L01C8
	ldx     #$00
	lda     #$FF
	jmp     incsp5
	.dbg	line, "listv.c", 216
L01C8:	ldy     #$04
	jsr     ldaxysp
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	jeq     L0179
	.dbg	line, "listv.c", 218
	ldy     #$02
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	ldy     #$00
	lda     (sp),y
	sta     (sreg),y
	.dbg	line, "listv.c", 219
	ldx     #$00
	lda     #$FE
	jmp     incsp5
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void LISTV_ReFresh (struct $anon-struct-0020*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_LISTV_ReFresh

	.dbg	line, "listv.c", 234
	ldy     #$01
	jsr     ldaxysp
	ldy     #$16
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L01D5
	.dbg	line, "listv.c", 236
	ldy     #$01
	jsr     ldaxysp
	ldy     #$17
	jsr     ldaxidx
	ldy     #$00
	jsr     callax
	.dbg	line, "listv.c", 238
L01D5:	ldy     #$01
	jsr     ldaxysp
	ldy     #$02
	jsr     ldaxidx
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$05
	jsr     ldaxysp
	ldy     #$06
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	ldy     #$07
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	jsr     _SCR_DrawWindow
	.dbg	line, "listv.c", 239
	jmp     incsp2
	.dbg	line

.endproc

