;
; File generated by cc65 v 2.8.0
;
	.fopt		compiler,"cc65 v 2.8.0"
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "menu.c", 6271, 1279048568
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdlib.h", 4033, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stddef.h", 2865, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdio.h", 5323, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/stdarg.h", 3007, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/string.h", 4335, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/conio.h", 7309, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/atari.h", 9513, 1030607464
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_gtia.h", 5733, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pbi.h", 3057, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pokey.h", 4268, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pia.h", 2655, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_antic.h", 3412, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/ctype.h", 7873, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/joystick.h", 3317, 1018643664
	.dbg		file, "plat.h", 1225, 1279048568
	.dbg		file, "type.h", 1140, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/cfg.h", 800, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/ptable.h", 2129, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/direntry.h", 4014, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/iso.h", 8718, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/idestruc.h", 1307, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/fatstruc.h", 3099, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/siocmds.h", 2388, 1279048570
	.dbg		file, "keys.h", 865, 1279048568
	.dbg		file, "siosrv.h", 1744, 1279048568
	.dbg		file, "screen.h", 1856, 1279048568
	.dbg		file, "menu.h", 1328, 1279048568
	.dbg		file, "listv.h", 1458, 1279048568
	.dbg		file, "qsort.h", 847, 1279048568
	.import		_strchr
	.import		_memset
	.import		_kbhit
	.import		_gotoxy
	.import		_cgetc
	.import		_readjoy
	.import		_SCR_DrawFrame
	.import		_SCR_LineCenter
	.import		_SCR_DrawLine
	.export		_MENU_Show
	.export		_MENU_Delay
	.export		_MENU_ReFresh

; ---------------------------------------------------------------
; unsigned char MENU_Show (struct $anon-struct-001F*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_MENU_Show

	.dbg	line, "menu.c", 216
	jsr     decsp2
	lda     #$00
	jsr     pusha
	.dbg	line, "menu.c", 217
	lda     #$00
	jsr     pusha
	.dbg	line, "menu.c", 221
	jsr     decsp2
	lda     #$00
	ldy     #$03
	sta     (sp),y
	.dbg	line, "menu.c", 222
	dey
	sta     (sp),y
	.dbg	line, "menu.c", 223
	ldy     #$07
	jsr     ldaxysp
	ldy     #$08
	jsr     ldaxidx
L0202:	ldy     #$04
	jsr     staxysp
	.dbg	line, "menu.c", 224
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	beq     L01B8
	.dbg	line, "menu.c", 226
	ldy     #$02
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	.dbg	line, "menu.c", 227
	ldy     #$05
	jsr     ldaxysp
	jsr     incax7
	.dbg	line, "menu.c", 228
	jmp     L0202
	.dbg	line, "menu.c", 229
L01B8:	ldy     #$09
	jsr     pushwysp
	jsr     _MENU_ReFresh
	.dbg	line, "menu.c", 233
L01C1:	ldy     #$09
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	jsr     _MENU_Draw
	.dbg	line, "menu.c", 234
	ldy     #$03
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	.dbg	line, "menu.c", 235
	ldy     #$09
	jsr     pushwysp
	lda     #$03
	jsr     leaasp
	jsr     pushax
	jsr     _MENU_WaitKey
	ldy     #$00
	sta     (sp),y
	.dbg	line, "menu.c", 264
	cmp     #$1C
	beq     L01E7
	cmp     #$1D
	beq     L01DB
	cmp     #$9B
	beq     L01F2
	cmp     #$FE
	beq     L01D1
	cmp     #$FF
	bne     L01C1
	.dbg	line, "menu.c", 238
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jmp     incsp8
	.dbg	line, "menu.c", 240
L01D1:	iny
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     tosicmp
	bcs     L01D5
	ldy     #$01
	jmp     L0200
L01D5:	ldy     #$03
L0200:	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	.dbg	line, "menu.c", 241
	jmp     L01C1
	.dbg	line, "menu.c", 243
L01DB:	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     decax1
	jsr     tosicmp
	bcs     L01E0
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     incax1
	jmp     L01E3
L01E0:	ldy     #$03
	lda     (sp),y
L01E3:	sta     (sp),y
	.dbg	line, "menu.c", 244
	jmp     L01C1
	.dbg	line, "menu.c", 246
L01E7:	ldy     #$03
	lda     (sp),y
	beq     L01EB
	ldx     #$00
	lda     (sp),y
	jsr     decax1
	jmp     L01EE
L01EB:	lda     (sp),y
L01EE:	sta     (sp),y
	.dbg	line, "menu.c", 247
	jmp     L01C1
	.dbg	line, "menu.c", 249
L01F2:	ldy     #$07
	jsr     ldaxysp
	ldy     #$08
	jsr     ldaxidx
	jsr     pushax
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     mulax7
	jsr     tosaddax
	ldy     #$04
	jsr     staxysp
	.dbg	line, "menu.c", 250
	ldy     #$05
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L01F7
	.dbg	line, "menu.c", 252
	dey
	jsr     ldaxysp
	ldy     #$06
	jsr     ldaxidx
	ldy     #$00
	jsr     callax
	tax
	beq     L01F7
	.dbg	line, "menu.c", 254
	ldy     #$09
	jsr     pushwysp
	jsr     _MENU_ReFresh
	.dbg	line, "menu.c", 257
L01F7:	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$02
	jne     L01C1
	.dbg	line, "menu.c", 259
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jmp     incsp8
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void MENU_Delay (unsigned long)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_MENU_Delay

	.dbg	line, "menu.c", 42
L00D5:	ldy     #$03
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     deceaxy
	dey
	jsr     steaxysp
	jsr     resteax
	jsr     utsteax
	jeq     incsp4
	.dbg	line, "menu.c", 44
	lda     #$00
	jsr     _readjoy
	.dbg	line, "menu.c", 45
	jmp     L00D5
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void MENU_DrawItem (unsigned char*, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_MENU_DrawItem

	.dbg	line, "menu.c", 57
	ldy     #$29
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	.dbg	line, "menu.c", 59
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldy     #$2D
	lda     (sp),y
	cmp     #$01
	bne     L00E2
	ldx     #$00
	lda     #$A0
	jmp     L00E4
L00E2:	ldx     #$00
	lda     #$20
L00E4:	jsr     pushax
	lda     #$28
	jsr     _memset
	.dbg	line, "menu.c", 60
L00E8:	ldy     #$2E
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	beq     L00E9
	.dbg	line, "menu.c", 62
	iny
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$2D
	lda     (sp),y
	cmp     #$01
	bne     L00EE
	ldy     #$30
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$32
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$1B
	bne     L00F1
	ldx     #$00
	txa
	jmp     L00F3
L00F1:	ldx     #$00
	lda     #$80
L00F3:	jsr     tosaddax
	jmp     L00F6
L00EE:	ldy     #$30
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
L00F6:	ldy     #$00
	jsr     staspidx
	.dbg	line, "menu.c", 63
	ldy     #$2E
	jsr     ldaxysp
	jsr     incax1
	ldy     #$2D
	jsr     staxysp
	.dbg	line, "menu.c", 64
	jmp     L00E8
	.dbg	line, "menu.c", 65
L00E9:	lda     #$02
	jsr     leaasp
	ldy     #$2C
	clc
	adc     (sp),y
	bcc     L00FC
	inx
L00FC:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	.dbg	line, "menu.c", 66
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldy     #$2E
	lda     (sp),y
	jsr     pusha
	jsr     _SCR_DrawLine
	.dbg	line, "menu.c", 67
	ldy     #$2F
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void MENU_Draw (struct $anon-struct-001F*, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_MENU_Draw

	.dbg	line, "menu.c", 81
	jsr     decsp5
	ldy     #$08
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$01
	bne     L0104
	ldy     #$08
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tossubax
	.dbg	line, "menu.c", 82
	jmp     L0203
L0104:	ldy     #$08
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tossubax
	jsr     decax1
	jsr     pushax
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	jsr     tosudivax
L0203:	jsr     decax1
	ldy     #$02
	sta     (sp),y
	.dbg	line, "menu.c", 83
	lda     #$00
	dey
	sta     (sp),y
	.dbg	line, "menu.c", 84
	ldy     #$08
	jsr     ldaxysp
	ldy     #$08
	jsr     ldaxidx
	ldy     #$03
	jsr     staxysp
	.dbg	line, "menu.c", 85
	ldy     #$08
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$01
	jne     L0110
	.dbg	line, "menu.c", 87
	ldy     #$08
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     incax1
	ldy     #$00
	sta     (sp),y
	.dbg	line, "menu.c", 88
L0114:	ldy     #$04
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jeq     L012C
	.dbg	line, "menu.c", 90
	ldy     #$08
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     incax1
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	jsr     _gotoxy
	.dbg	line, "menu.c", 91
	ldy     #$04
	jsr     ldaxysp
	ldy     #$02
	jsr     ldaxidx
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$0A
	lda     (sp),y
	jsr     tosicmp
	bne     L011F
	lda     #$01
	jmp     L0121
L011F:	lda     #$00
L0121:	jsr     pusha
	jsr     _MENU_DrawItem
	.dbg	line, "menu.c", 92
	ldy     #$04
	jsr     ldaxysp
	jsr     incax7
	ldy     #$03
	jsr     staxysp
	.dbg	line, "menu.c", 93
	ldy     #$01
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	.dbg	line, "menu.c", 94
	jmp     L0114
	.dbg	line, "menu.c", 96
L0110:	ldy     #$08
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	cmp     #$02
	jne     L012C
	.dbg	line, "menu.c", 98
	ldy     #$08
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     incax1
	ldy     #$00
	sta     (sp),y
	.dbg	line, "menu.c", 99
L012B:	ldy     #$04
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	beq     L012C
	.dbg	line, "menu.c", 101
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     incax1
	jsr     _gotoxy
	.dbg	line, "menu.c", 102
	ldy     #$04
	jsr     ldaxysp
	ldy     #$02
	jsr     ldaxidx
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$0A
	lda     (sp),y
	jsr     tosicmp
	bne     L0136
	lda     #$01
	jmp     L0138
L0136:	lda     #$00
L0138:	jsr     pusha
	jsr     _MENU_DrawItem
	.dbg	line, "menu.c", 103
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     incax2
	ldy     #$00
	clc
	adc     (sp),y
	sta     (sp),y
	.dbg	line, "menu.c", 104
	ldy     #$04
	jsr     ldaxysp
	jsr     incax7
	ldy     #$03
	jsr     staxysp
	.dbg	line, "menu.c", 105
	ldy     #$01
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	.dbg	line, "menu.c", 106
	jmp     L012B
	.dbg	line, "menu.c", 108
L012C:	ldy     #$09
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char MENU_WaitKey (struct $anon-struct-001F*, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_MENU_WaitKey

	.dbg	line, "menu.c", 122
	jsr     decsp4
	.dbg	line, "menu.c", 124
L0143:	lda     #$FF
	ldy     #$01
	sta     (sp),y
	.dbg	line, "menu.c", 125
	jsr     _kbhit
	tax
	beq     L0146
	.dbg	line, "menu.c", 127
	jsr     _cgetc
	ldy     #$01
	sta     (sp),y
	.dbg	line, "menu.c", 130
L0146:	lda     #$00
	jsr     _readjoy
	.dbg	line, "menu.c", 145
	cpx     #$00
	bne     L014C
	cmp     #$01
	beq     L014E
	cmp     #$02
	beq     L0154
	cmp     #$04
	beq     L014E
	cmp     #$08
	beq     L0154
	cmp     #$10
	beq     L015A
	jmp     L014C
	.dbg	line, "menu.c", 134
L014E:	lda     #$1C
	.dbg	line, "menu.c", 135
	jmp     L0205
	.dbg	line, "menu.c", 138
L0154:	lda     #$1D
	.dbg	line, "menu.c", 139
	jmp     L0205
	.dbg	line, "menu.c", 141
L015A:	lda     #$9B
L0205:	ldy     #$01
	sta     (sp),y
	.dbg	line, "menu.c", 146
L014C:	ldy     #$01
	lda     (sp),y
	.dbg	line, "menu.c", 186
	beq     L0143
	cmp     #$1C
	beq     L016A
	cmp     #$1D
	beq     L0179
	cmp     #$1E
	beq     L016A
	cmp     #$1F
	beq     L0179
	cmp     #$2A
	beq     L0179
	cmp     #$2B
	beq     L016A
	cmp     #$2D
	beq     L016A
	cmp     #$3D
	beq     L0179
	cmp     #$9B
	beq     L0165
	cmp     #$9C
	beq     L016A
	cmp     #$9D
	beq     L0179
	cmp     #$9E
	beq     L016A
	cmp     #$9F
	beq     L0179
	cmp     #$FF
	jeq     L0143
	jmp     L0187
	.dbg	line, "menu.c", 152
L0165:	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$64
	jsr     pusheax
	jsr     _MENU_Delay
	.dbg	line, "menu.c", 153
	ldx     #$00
	lda     #$9B
	jmp     incsp8
	.dbg	line, "menu.c", 160
L016A:	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$64
	jsr     pusheax
	jsr     _MENU_Delay
	.dbg	line, "menu.c", 161
	ldx     #$00
	lda     #$1C
	jmp     incsp8
	.dbg	line, "menu.c", 168
L0179:	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$32
	jsr     pusheax
	jsr     _MENU_Delay
	.dbg	line, "menu.c", 169
	ldx     #$00
	lda     #$1D
	jmp     incsp8
	.dbg	line, "menu.c", 171
L0187:	ldy     #$07
	jsr     ldaxysp
	ldy     #$0A
	jsr     ldaxidx
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	beq     L0188
	ldx     #$00
	lda     #$FF
	jmp     incsp8
	.dbg	line, "menu.c", 173
L0188:	ldy     #$07
	jsr     ldaxysp
	ldy     #$08
	jsr     ldaxidx
	ldy     #$02
	jsr     staxysp
	.dbg	line, "menu.c", 174
	lda     #$00
	tay
	sta     (sp),y
	.dbg	line, "menu.c", 175
L0191:	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jeq     L0143
	.dbg	line, "menu.c", 177
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     ldaxidx
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     _strchr
	stx     tmp1
	ora     tmp1
	beq     L0194
	.dbg	line, "menu.c", 179
	ldy     #$05
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	ldy     #$00
	lda     (sp),y
	sta     (sreg),y
	.dbg	line, "menu.c", 180
	ldx     #$00
	lda     #$FE
	jmp     incsp8
	.dbg	line, "menu.c", 182
L0194:	ldy     #$03
	jsr     ldaxysp
	jsr     incax7
	ldy     #$02
	jsr     staxysp
	.dbg	line, "menu.c", 183
	ldy     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	.dbg	line, "menu.c", 184
	jmp     L0191
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void MENU_ReFresh (struct $anon-struct-001F*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_MENU_ReFresh

	.dbg	line, "menu.c", 198
	ldy     #$01
	jsr     ldaxysp
	ldy     #$0B
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L019E
	.dbg	line, "menu.c", 200
	ldy     #$01
	jsr     ldaxysp
	ldy     #$0C
	jsr     ldaxidx
	ldy     #$00
	jsr     callax
	.dbg	line, "menu.c", 202
L019E:	ldy     #$01
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	ldy     #$06
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _SCR_DrawFrame
	.dbg	line, "menu.c", 203
	ldy     #$01
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     incax1
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	ldy     #$04
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     _gotoxy
	.dbg	line, "menu.c", 204
	ldy     #$01
	jsr     ldaxysp
	ldy     #$02
	jsr     ldaxidx
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$05
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$03
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1),y
	jsr     tossubax
	jsr     decax1
	jsr     pusha
	jsr     _SCR_LineCenter
	.dbg	line, "menu.c", 205
	jmp     incsp2
	.dbg	line

.endproc

