;
; File generated by cc65 v 2.8.0
;
	.fopt		compiler,"cc65 v 2.8.0"
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "siosrv.c", 13843, 1279048568
	.dbg		file, "plat.h", 1225, 1279048568
	.dbg		file, "type.h", 1140, 1279048570
	.dbg		file, "C:\Work\CMPLRS\cc65\include/atari.h", 9513, 1030607464
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_gtia.h", 5733, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pbi.h", 3057, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pokey.h", 4268, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_pia.h", 2655, 1018643664
	.dbg		file, "C:\Work\CMPLRS\cc65\include/_antic.h", 3412, 1018643664
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/cfg.h", 800, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/ptable.h", 2129, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/direntry.h", 4014, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/iso.h", 8718, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/idestruc.h", 1307, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/fatstruc.h", 3099, 1279048570
	.dbg		file, "C:\Work\Projects\SIO2IDE\\VER.400\SOFT\AVR\FAT_1632/siocmds.h", 2388, 1279048570
	.dbg		file, "keys.h", 865, 1279048568
	.dbg		file, "siosrv.h", 1744, 1279048568
	.dbg		file, "screen.h", 1856, 1279048568
	.dbg		file, "menu.h", 1328, 1279048568
	.dbg		file, "listv.h", 1458, 1279048568
	.dbg		file, "qsort.h", 847, 1279048568
	.export		_SIO_GetFSInfo
	.export		_SIO_GetDriveInfo
	.export		_SIO_GetNextATR
	.export		_SIO_GetFirstATR
	.export		_SIO_PutDisk
	.export		_SIO_GetDisk
	.export		_SIO_DiskOff
	.export		_SIO_SaveConfig
	.export		_SIO_GetFirstDir
	.export		_SIO_GetNextDir
	.export		_SIO_SetCurDir
	.export		_SIO_GetCurDir
	.export		_SIO_InitCurDir
	.export		_SIO_PutSect
	.export		_SIO_GetSect
	.export		_SIO_GetLFN
	.import		_siov

; ---------------------------------------------------------------
; unsigned char SIO_GetFSInfo (unsigned char, struct $anon-struct-0015*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetFSInfo

	.dbg	line, "siosrv.c", 199
	jsr     decsp5
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 200
	ldy     #$07
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 201
	lda     #$18
	sta     $0302
	.dbg	line, "siosrv.c", 202
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 203
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 204
	lda     #$05
	sta     $0306
	.dbg	line, "siosrv.c", 205
	ldx     #$00
	lda     #$04
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 207
	jsr     _siov
	ldy     #$04
	sta     (sp),y
	cmp     #$00
	beq     L0183
	.dbg	line, "siosrv.c", 209
	ldx     #$00
	txa
	jmp     incsp8
	.dbg	line, "siosrv.c", 211
L0183:	ldy     #$08
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     _memcpy
	.dbg	line, "siosrv.c", 212
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 213
	jmp     incsp8
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetDriveInfo (unsigned char, struct $anon-struct-0011*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetDriveInfo

	.dbg	line, "siosrv.c", 168
	ldy     #$0B
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 169
	ldy     #$0D
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 170
	lda     #$17
	sta     $0302
	.dbg	line, "siosrv.c", 171
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 172
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 173
	lda     #$05
	sta     $0306
	.dbg	line, "siosrv.c", 174
	ldx     #$00
	lda     #$0A
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 176
	jsr     _siov
	ldy     #$0A
	sta     (sp),y
	cmp     #$00
	beq     L0165
	.dbg	line, "siosrv.c", 178
	ldx     #$00
	txa
	jmp     L014F
	.dbg	line, "siosrv.c", 180
L0165:	ldy     #$0E
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _memcpy
	.dbg	line, "siosrv.c", 181
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 182
L014F:	ldy     #$0E
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetNextATR (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetNextATR

	.dbg	line, "siosrv.c", 137
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 138
	ldy     #$12
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 139
	lda     #$14
	sta     $0302
	.dbg	line, "siosrv.c", 140
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 141
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 142
	lda     #$0A
	sta     $0306
	.dbg	line, "siosrv.c", 143
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 145
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L0147
	.dbg	line, "siosrv.c", 147
	ldx     #$00
	txa
	jmp     L0131
	.dbg	line, "siosrv.c", 149
L0147:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 150
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 151
L0131:	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetFirstATR (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetFirstATR

	.dbg	line, "siosrv.c", 106
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 107
	ldy     #$12
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 108
	lda     #$13
	sta     $0302
	.dbg	line, "siosrv.c", 109
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 110
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 111
	lda     #$0A
	sta     $0306
	.dbg	line, "siosrv.c", 112
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 114
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L0129
	.dbg	line, "siosrv.c", 116
	ldx     #$00
	txa
	jmp     L0113
	.dbg	line, "siosrv.c", 118
L0129:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 119
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 120
L0113:	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_PutDisk (unsigned char, unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_PutDisk

	.dbg	line, "siosrv.c", 75
	jsr     decsp1
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 76
	ldy     #$04
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 77
	lda     #$12
	sta     $0302
	.dbg	line, "siosrv.c", 78
	dey
	lda     (sp),y
	sta     $030A
	.dbg	line, "siosrv.c", 79
	lda     #$80
	sta     $0303
	.dbg	line, "siosrv.c", 80
	dey
	jsr     ldaxysp
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 81
	lda     #$1E
	sta     $0306
	.dbg	line, "siosrv.c", 82
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 84
	jsr     _siov
	ldy     #$00
	sta     (sp),y
	cmp     #$00
	beq     L010D
	.dbg	line, "siosrv.c", 86
	ldx     #$00
	txa
	jmp     incsp5
	.dbg	line, "siosrv.c", 88
L010D:	tax
	lda     #$01
	.dbg	line, "siosrv.c", 89
	jmp     incsp5
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetDisk (unsigned char, unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetDisk

	.dbg	line, "siosrv.c", 44
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 45
	ldy     #$13
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 46
	lda     #$11
	sta     $0302
	.dbg	line, "siosrv.c", 47
	dey
	lda     (sp),y
	sta     $030A
	.dbg	line, "siosrv.c", 48
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 49
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 50
	lda     #$14
	sta     $0306
	.dbg	line, "siosrv.c", 51
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 53
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L00EC
	.dbg	line, "siosrv.c", 55
	ldx     #$00
	txa
	jmp     L00D3
	.dbg	line, "siosrv.c", 57
L00EC:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 58
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 59
L00D3:	ldy     #$14
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_DiskOff (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_DiskOff

	.dbg	line, "siosrv.c", 229
	jsr     decsp1
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 230
	ldy     #$02
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 231
	lda     #$15
	sta     $0302
	.dbg	line, "siosrv.c", 232
	dey
	lda     (sp),y
	sta     $030A
	.dbg	line, "siosrv.c", 233
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 234
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 235
	lda     #$05
	sta     $0306
	.dbg	line, "siosrv.c", 236
	ldx     #$00
	tya
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 238
	jsr     _siov
	cmp     #$00
	beq     L01A4
	.dbg	line, "siosrv.c", 240
	ldx     #$00
	txa
	jmp     incsp3
	.dbg	line, "siosrv.c", 242
L01A4:	tay
	lda     (sp),y
	cmp     #$FF
	beq     L01A7
	.dbg	line, "siosrv.c", 244
	ldx     #$00
	txa
	jmp     incsp3
	.dbg	line, "siosrv.c", 246
L01A7:	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 247
	jmp     incsp3
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_SaveConfig (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_SaveConfig

	.dbg	line, "siosrv.c", 263
	jsr     decsp1
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 264
	ldy     #$01
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 265
	lda     #$16
	sta     $0302
	.dbg	line, "siosrv.c", 266
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 267
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 268
	lda     #$1E
	sta     $0306
	.dbg	line, "siosrv.c", 269
	ldx     #$00
	tya
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 271
	jsr     _siov
	cmp     #$00
	beq     L01C1
	.dbg	line, "siosrv.c", 273
	ldx     #$00
	txa
	jmp     incsp2
	.dbg	line, "siosrv.c", 275
L01C1:	tay
	lda     (sp),y
	cmp     #$FF
	beq     L01C4
	.dbg	line, "siosrv.c", 277
	ldx     #$00
	txa
	jmp     incsp2
	.dbg	line, "siosrv.c", 279
L01C4:	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 280
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetFirstDir (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetFirstDir

	.dbg	line, "siosrv.c", 297
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 298
	ldy     #$12
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 299
	lda     #$19
	sta     $0302
	.dbg	line, "siosrv.c", 300
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 301
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 302
	lda     #$0A
	sta     $0306
	.dbg	line, "siosrv.c", 303
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 305
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L01DE
	.dbg	line, "siosrv.c", 307
	ldx     #$00
	txa
	jmp     L01C8
	.dbg	line, "siosrv.c", 309
L01DE:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 310
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 311
L01C8:	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetNextDir (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetNextDir

	.dbg	line, "siosrv.c", 328
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 329
	ldy     #$12
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 330
	lda     #$1A
	sta     $0302
	.dbg	line, "siosrv.c", 331
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 332
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 333
	lda     #$0A
	sta     $0306
	.dbg	line, "siosrv.c", 334
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 336
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L01FC
	.dbg	line, "siosrv.c", 338
	ldx     #$00
	txa
	jmp     L01E6
	.dbg	line, "siosrv.c", 340
L01FC:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 341
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 342
L01E6:	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_SetCurDir (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_SetCurDir

	.dbg	line, "siosrv.c", 358
	jsr     decsp1
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 359
	ldy     #$03
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 360
	lda     #$1B
	sta     $0302
	.dbg	line, "siosrv.c", 361
	lda     #$80
	sta     $0303
	.dbg	line, "siosrv.c", 362
	dey
	jsr     ldaxysp
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 363
	lda     #$0A
	sta     $0306
	.dbg	line, "siosrv.c", 364
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 366
	jsr     _siov
	ldy     #$00
	sta     (sp),y
	cmp     #$00
	beq     L021A
	.dbg	line, "siosrv.c", 368
	ldx     #$00
	txa
	jmp     incsp4
	.dbg	line, "siosrv.c", 370
L021A:	tax
	lda     #$01
	.dbg	line, "siosrv.c", 371
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetCurDir (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetCurDir

	.dbg	line, "siosrv.c", 388
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 389
	ldy     #$12
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 390
	lda     #$1C
	sta     $0302
	.dbg	line, "siosrv.c", 391
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 392
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 393
	lda     #$0A
	sta     $0306
	.dbg	line, "siosrv.c", 394
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 396
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L0236
	.dbg	line, "siosrv.c", 398
	ldx     #$00
	txa
	jmp     L0220
	.dbg	line, "siosrv.c", 400
L0236:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 401
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 402
L0220:	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_InitCurDir (unsigned char, struct $anon-struct-0013*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_InitCurDir

	.dbg	line, "siosrv.c", 419
	ldy     #$10
	jsr     subysp
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 420
	ldy     #$12
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 421
	lda     #$1D
	sta     $0302
	.dbg	line, "siosrv.c", 422
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 423
	lda     sp
	ldx     sp+1
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 424
	lda     #$5A
	sta     $0306
	.dbg	line, "siosrv.c", 425
	ldx     #$00
	lda     #$0F
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 427
	jsr     _siov
	ldy     #$0F
	sta     (sp),y
	cmp     #$00
	beq     L0254
	.dbg	line, "siosrv.c", 429
	ldx     #$00
	txa
	jmp     L023E
	.dbg	line, "siosrv.c", 431
L0254:	ldy     #$13
	jsr     pushwysp
	lda     #$02
	jsr     leaasp
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     _memcpy
	.dbg	line, "siosrv.c", 432
	ldx     #$00
	lda     #$01
	.dbg	line, "siosrv.c", 433
L023E:	ldy     #$13
	jmp     addysp
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_PutSect (unsigned char, unsigned long, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_PutSect

	.dbg	line, "siosrv.c", 478
	jsr     decsp1
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	jsr     _SIO_SetSect
	tax
	.dbg	line, "siosrv.c", 479
	jeq     incsp8
	.dbg	line, "siosrv.c", 481
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 482
	ldy     #$07
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 483
	lda     #$63
	sta     $0302
	.dbg	line, "siosrv.c", 484
	lda     #$80
	sta     $0303
	.dbg	line, "siosrv.c", 485
	ldy     #$02
	jsr     ldaxysp
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 486
	lda     #$1E
	sta     $0306
	.dbg	line, "siosrv.c", 487
	ldx     #$02
	lda     #$00
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 489
	jsr     _siov
	ldy     #$00
	sta     (sp),y
	cmp     #$00
	beq     L0293
	.dbg	line, "siosrv.c", 491
	ldx     #$00
	txa
	jmp     incsp8
	.dbg	line, "siosrv.c", 493
L0293:	tax
	lda     #$01
	.dbg	line, "siosrv.c", 494
	jmp     incsp8
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetSect (unsigned char, unsigned long, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetSect

	.dbg	line, "siosrv.c", 510
	jsr     decsp1
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	jsr     _SIO_SetSect
	tax
	.dbg	line, "siosrv.c", 511
	jeq     incsp8
	.dbg	line, "siosrv.c", 513
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 514
	ldy     #$07
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 515
	lda     #$62
	sta     $0302
	.dbg	line, "siosrv.c", 516
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 517
	ldy     #$02
	jsr     ldaxysp
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 518
	lda     #$1E
	sta     $0306
	.dbg	line, "siosrv.c", 519
	ldx     #$02
	lda     #$00
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 521
	jsr     _siov
	ldy     #$00
	sta     (sp),y
	cmp     #$00
	beq     L02B4
	.dbg	line, "siosrv.c", 523
	ldx     #$00
	txa
	jmp     incsp8
	.dbg	line, "siosrv.c", 525
L02B4:	tax
	lda     #$01
	.dbg	line, "siosrv.c", 526
	jmp     incsp8
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_GetLFN (unsigned char, unsigned long, unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_GetLFN

	.dbg	line, "siosrv.c", 542
	jsr     decsp1
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	jsr     _SIO_SetSect
	tax
	.dbg	line, "siosrv.c", 543
	jeq     incsp8
	.dbg	line, "siosrv.c", 545
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 546
	ldy     #$07
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 547
	lda     #$64
	sta     $0302
	.dbg	line, "siosrv.c", 548
	lda     #$40
	sta     $0303
	.dbg	line, "siosrv.c", 549
	ldy     #$02
	jsr     ldaxysp
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 550
	lda     #$1E
	sta     $0306
	.dbg	line, "siosrv.c", 551
	ldx     #$00
	lda     #$27
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 553
	jsr     _siov
	ldy     #$00
	sta     (sp),y
	cmp     #$00
	beq     L02D6
	.dbg	line, "siosrv.c", 555
	ldx     #$00
	txa
	jmp     incsp8
	.dbg	line, "siosrv.c", 557
L02D6:	tax
	lda     #$01
	.dbg	line, "siosrv.c", 558
	jmp     incsp8
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char SIO_SetSect (unsigned char, unsigned long)
; ---------------------------------------------------------------

.segment	"CODE2"

.proc	_SIO_SetSect

	.dbg	line, "siosrv.c", 449
	jsr     decsp1
	lda     #$71
	sta     $0300
	.dbg	line, "siosrv.c", 450
	ldy     #$05
	lda     (sp),y
	sta     $0301
	.dbg	line, "siosrv.c", 451
	lda     #$61
	sta     $0302
	.dbg	line, "siosrv.c", 452
	lda     #$80
	sta     $0303
	.dbg	line, "siosrv.c", 453
	lda     #$01
	jsr     leaasp
	sta     $0304
	stx     $0304+1
	.dbg	line, "siosrv.c", 454
	lda     #$14
	sta     $0306
	.dbg	line, "siosrv.c", 455
	ldx     #$00
	lda     #$04
	sta     $0308
	stx     $0308+1
	.dbg	line, "siosrv.c", 457
	jsr     _siov
	ldy     #$00
	sta     (sp),y
	cmp     #$00
	beq     L0272
	.dbg	line, "siosrv.c", 459
	ldx     #$00
	txa
	jmp     incsp6
	.dbg	line, "siosrv.c", 461
L0272:	tax
	lda     #$01
	.dbg	line, "siosrv.c", 462
	jmp     incsp6
	.dbg	line

.endproc

