//****************************************************************
// Copyright (C), 2001 MMSoft, All rights reserved
//****************************************************************

//****************************************************************
//
// SOURCE FILE: types.h
//
// MODULE NAME: common
//
// PURPOSE:     Predefined common data types.
//
// AUTHOR:      Marek Mikolajewski (MM)
//
// REVIEWED BY:
//
// HISTORY:     Ver   Date       Sign   Description
//
//              001    6-12-2001 MM     Created
//
//****************************************************************

#ifndef __TYPES_H__
  #define __TYPES_H__

typedef char            INT8;
typedef short           INT16;
typedef long            INT32;
typedef unsigned char   UINT8;
typedef unsigned int    UINT16;
typedef unsigned long   UINT32;
typedef unsigned char   BOOL;

#endif  // __TYPES_H__
